package net.b34tzepz.betterbuilding.item.custom;

import com.google.common.collect.ImmutableMap;
import com.google.common.collect.Maps;
import net.b34tzepz.betterbuilding.block.ModBlocks;
import net.b34tzepz.betterbuilding.block.custom.PillarBlock;
import net.minecraft.block.Block;
import net.minecraft.block.BlockState;
import net.minecraft.block.Blocks;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.item.Item;
import net.minecraft.item.ItemUsageContext;
import net.minecraft.sound.SoundCategory;
import net.minecraft.sound.SoundEvents;
import net.minecraft.util.ActionResult;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.Direction;
import net.minecraft.world.World;

import java.util.Map;

public class ChiselItem extends Item {
    public static final Map<Block, Block> PILLAR_BLOCKS = new ImmutableMap.Builder<Block, Block>()
            .put(Blocks.STONE, ModBlocks.Pillars.STONE_PILLAR)
            .put(Blocks.GRANITE, ModBlocks.Pillars.GRANITE_PILLAR)
            .put(Blocks.POLISHED_GRANITE, ModBlocks.Pillars.POLISHED_GRANITE_PILLAR)
            .put(Blocks.DIORITE, ModBlocks.Pillars.DIORITE_PILLAR)
            .put(Blocks.POLISHED_DIORITE, ModBlocks.Pillars.POLISHED_DIORITE_PILLAR)
            .put(Blocks.ANDESITE, ModBlocks.Pillars.ANDESITE_PILLAR)
            .put(Blocks.POLISHED_ANDESITE, ModBlocks.Pillars.POLISHED_ANDESITE_PILLAR)
            .put(Blocks.DEEPSLATE, ModBlocks.Pillars.DEEPSLATE_PILLAR)
            .put(Blocks.DIRT, ModBlocks.Pillars.DIRT_PILLAR)
            .put(Blocks.COARSE_DIRT, ModBlocks.Pillars.COARSE_DIRT_PILLAR)
            .put(Blocks.MUD, ModBlocks.Pillars.MUD_PILLAR)
            .put(Blocks.COBBLESTONE, ModBlocks.Pillars.COBBLESTONE_PILLAR)
            .put(Blocks.OAK_PLANKS, ModBlocks.Pillars.OAK_PLANK_PILLAR)
            .put(Blocks.SPRUCE_PLANKS, ModBlocks.Pillars.SPRUCE_PLANK_PILLAR)
            .put(Blocks.BIRCH_PLANKS, ModBlocks.Pillars.BIRCH_PLANK_PILLAR)
            .put(Blocks.JUNGLE_PLANKS, ModBlocks.Pillars.JUNGLE_PLANK_PILLAR)
            .put(Blocks.ACACIA_PLANKS, ModBlocks.Pillars.ACACIA_PLANK_PILLAR)
            .put(Blocks.DARK_OAK_PLANKS, ModBlocks.Pillars.DARK_OAK_PLANK_PILLAR)
            .put(Blocks.MANGROVE_PLANKS, ModBlocks.Pillars.MANGROVE_PLANK_PILLAR)
            .put(Blocks.BEDROCK, ModBlocks.Pillars.BEDROCK_PILLAR)
            .put(Blocks.LAPIS_BLOCK, ModBlocks.Pillars.LAPIS_PILLAR)
            .put(Blocks.SANDSTONE, ModBlocks.Pillars.SANDSTONE_PILLAR)
            .put(Blocks.CHISELED_SANDSTONE, ModBlocks.Pillars.CHISELED_SANDSTONE_PILLAR)
            .put(Blocks.CUT_SANDSTONE, ModBlocks.Pillars.CUT_SANDSTONE_PILLAR)
            .put(Blocks.WHITE_WOOL, ModBlocks.Pillars.WHITE_WOOL_PILLAR)
            .put(Blocks.ORANGE_WOOL, ModBlocks.Pillars.ORANGE_WOOL_PILLAR)
            .put(Blocks.MAGENTA_WOOL, ModBlocks.Pillars.MAGENTA_WOOL_PILLAR)
            .put(Blocks.LIGHT_BLUE_WOOL, ModBlocks.Pillars.LIGHT_BLUE_WOOL_PILLAR)
            .put(Blocks.YELLOW_WOOL, ModBlocks.Pillars.YELLOW_WOOL_PILLAR)
            .put(Blocks.LIME_WOOL, ModBlocks.Pillars.LIME_WOOL_PILLAR)
            .put(Blocks.PINK_WOOL, ModBlocks.Pillars.PINK_WOOL_PILLAR)
            .put(Blocks.GRAY_WOOL, ModBlocks.Pillars.GRAY_WOOL_PILLAR)
            .put(Blocks.LIGHT_GRAY_WOOL, ModBlocks.Pillars.LIGHT_GRAY_WOOL_PILLAR)
            .put(Blocks.CYAN_WOOL, ModBlocks.Pillars.CYAN_WOOL_PILLAR)
            .put(Blocks.PURPLE_WOOL, ModBlocks.Pillars.PURPLE_WOOL_PILLAR)
            .put(Blocks.BLUE_WOOL, ModBlocks.Pillars.BLUE_WOOL_PILLAR)
            .put(Blocks.BROWN_WOOL, ModBlocks.Pillars.BROWN_WOOL_PILLAR)
            .put(Blocks.GREEN_WOOL, ModBlocks.Pillars.GREEN_WOOL_PILLAR)
            .put(Blocks.RED_WOOL, ModBlocks.Pillars.RED_WOOL_PILLAR)
            .put(Blocks.BLACK_WOOL, ModBlocks.Pillars.BLACK_WOOL_PILLAR)
            .put(Blocks.GOLD_BLOCK, ModBlocks.Pillars.GOLD_PILLAR)
            .put(Blocks.IRON_BLOCK, ModBlocks.Pillars.IRON_PILLAR)
            .put(Blocks.COPPER_BLOCK, ModBlocks.Pillars.COPPER_PILLAR)
            .put(Blocks.BRICKS, ModBlocks.Pillars.BRICK_PILLAR)
            .put(Blocks.BOOKSHELF, ModBlocks.Pillars.BOOKSHELF_PILLAR)
            .put(Blocks.MOSSY_COBBLESTONE, ModBlocks.Pillars.MOSSY_COBBLESTONE_PILLAR)
            .put(Blocks.OBSIDIAN, ModBlocks.Pillars.OBSIDIAN_PILLAR)
            .put(Blocks.DIAMOND_BLOCK, ModBlocks.Pillars.DIAMOND_PILLAR)
            .put(Blocks.SNOW_BLOCK, ModBlocks.Pillars.SNOW_PILLAR)
            .put(Blocks.CLAY, ModBlocks.Pillars.CLAY_PILLAR)
            .put(Blocks.SOUL_SAND, ModBlocks.Pillars.SOUL_SAND_PILLAR)
            .put(Blocks.SOUL_SOIL, ModBlocks.Pillars.SOUL_SOIL_PILLAR)
            .put(Blocks.BASALT, ModBlocks.Pillars.BASALT_PILLAR)
            .put(Blocks.POLISHED_BASALT, ModBlocks.Pillars.POLISHED_BASALT_PILLAR)
            .put(Blocks.GLOWSTONE, ModBlocks.Pillars.GLOWSTONE_PILLAR)
            .put(Blocks.STONE_BRICKS, ModBlocks.Pillars.STONE_BRICK_PILLAR)
            .put(Blocks.MOSSY_STONE_BRICKS, ModBlocks.Pillars.MOSSY_STONE_BRICK_PILLAR)
            .put(Blocks.CRACKED_STONE_BRICKS, ModBlocks.Pillars.CRACKED_STONE_BRICK_PILLAR)
            .put(Blocks.CHISELED_STONE_BRICKS, ModBlocks.Pillars.CHISELED_STONE_BRICK_PILLAR)
            .put(Blocks.PACKED_MUD, ModBlocks.Pillars.PACKED_MUD_PILLAR)
            .put(Blocks.MUD_BRICKS, ModBlocks.Pillars.MUD_BRICK_PILLAR)
            .put(Blocks.NETHER_BRICKS, ModBlocks.Pillars.NETHER_BRICK_PILLAR)
            .put(Blocks.END_STONE, ModBlocks.Pillars.END_STONE_PILLAR)
            .put(Blocks.EMERALD_BLOCK, ModBlocks.Pillars.EMERALD_PILLAR)
            .put(Blocks.QUARTZ_BLOCK, ModBlocks.Pillars.QUARTZ_PILLAR)
            .put(Blocks.CHISELED_QUARTZ_BLOCK, ModBlocks.Pillars.CHISELED_QUARTZ_PILLAR)
            .put(Blocks.WHITE_TERRACOTTA, ModBlocks.Pillars.WHITE_TERRACOTTA_PILLAR)
            .put(Blocks.ORANGE_TERRACOTTA, ModBlocks.Pillars.ORANGE_TERRACOTTA_PILLAR)
            .put(Blocks.MAGENTA_TERRACOTTA, ModBlocks.Pillars.MAGENTA_TERRACOTTA_PILLAR)
            .put(Blocks.LIGHT_BLUE_TERRACOTTA, ModBlocks.Pillars.LIGHT_BLUE_TERRACOTTA_PILLAR)
            .put(Blocks.YELLOW_TERRACOTTA, ModBlocks.Pillars.YELLOW_TERRACOTTA_PILLAR)
            .put(Blocks.LIME_TERRACOTTA, ModBlocks.Pillars.LIME_TERRACOTTA_PILLAR)
            .put(Blocks.PINK_TERRACOTTA, ModBlocks.Pillars.PINK_TERRACOTTA_PILLAR)
            .put(Blocks.GRAY_TERRACOTTA, ModBlocks.Pillars.GRAY_TERRACOTTA_PILLAR)
            .put(Blocks.LIGHT_GRAY_TERRACOTTA, ModBlocks.Pillars.LIGHT_GRAY_TERRACOTTA_PILLAR)
            .put(Blocks.CYAN_TERRACOTTA, ModBlocks.Pillars.CYAN_TERRACOTTA_PILLAR)
            .put(Blocks.PURPLE_TERRACOTTA, ModBlocks.Pillars.PURPLE_TERRACOTTA_PILLAR)
            .put(Blocks.BLUE_TERRACOTTA, ModBlocks.Pillars.BLUE_TERRACOTTA_PILLAR)
            .put(Blocks.BROWN_TERRACOTTA, ModBlocks.Pillars.BROWN_TERRACOTTA_PILLAR)
            .put(Blocks.GREEN_TERRACOTTA, ModBlocks.Pillars.GREEN_TERRACOTTA_PILLAR)
            .put(Blocks.RED_TERRACOTTA, ModBlocks.Pillars.RED_TERRACOTTA_PILLAR)
            .put(Blocks.BLACK_TERRACOTTA, ModBlocks.Pillars.BLACK_TERRACOTTA_PILLAR)
            .put(Blocks.HAY_BLOCK, ModBlocks.Pillars.HAY_PILLAR)
            .put(Blocks.WHITE_STAINED_GLASS, ModBlocks.Pillars.WHITE_STAINED_GLASS_PILLAR)
            .put(Blocks.ORANGE_STAINED_GLASS, ModBlocks.Pillars.ORANGE_STAINED_GLASS_PILLAR)
            .put(Blocks.MAGENTA_STAINED_GLASS, ModBlocks.Pillars.MAGENTA_STAINED_GLASS_PILLAR)
            .put(Blocks.LIGHT_BLUE_STAINED_GLASS, ModBlocks.Pillars.LIGHT_BLUE_STAINED_GLASS_PILLAR)
            .put(Blocks.YELLOW_STAINED_GLASS, ModBlocks.Pillars.YELLOW_STAINED_GLASS_PILLAR)
            .put(Blocks.LIME_STAINED_GLASS, ModBlocks.Pillars.LIME_STAINED_GLASS_PILLAR)
            .put(Blocks.PINK_STAINED_GLASS, ModBlocks.Pillars.PINK_STAINED_GLASS_PILLAR)
            .put(Blocks.GRAY_STAINED_GLASS, ModBlocks.Pillars.GRAY_STAINED_GLASS_PILLAR)
            .put(Blocks.LIGHT_GRAY_STAINED_GLASS, ModBlocks.Pillars.LIGHT_GRAY_STAINED_GLASS_PILLAR)
            .put(Blocks.CYAN_STAINED_GLASS, ModBlocks.Pillars.CYAN_STAINED_GLASS_PILLAR)
            .put(Blocks.PURPLE_STAINED_GLASS, ModBlocks.Pillars.PURPLE_STAINED_GLASS_PILLAR)
            .put(Blocks.BLUE_STAINED_GLASS, ModBlocks.Pillars.BLUE_STAINED_GLASS_PILLAR)
            .put(Blocks.BROWN_STAINED_GLASS, ModBlocks.Pillars.BROWN_STAINED_GLASS_PILLAR)
            .put(Blocks.GREEN_STAINED_GLASS, ModBlocks.Pillars.GREEN_STAINED_GLASS_PILLAR)
            .put(Blocks.RED_STAINED_GLASS, ModBlocks.Pillars.RED_STAINED_GLASS_PILLAR)
            .put(Blocks.BLACK_STAINED_GLASS, ModBlocks.Pillars.BLACK_STAINED_GLASS_PILLAR)
            .put(Blocks.PRISMARINE, ModBlocks.Pillars.PRISMARINE_PILLAR)
            .put(Blocks.PRISMARINE_BRICKS, ModBlocks.Pillars.PRISMARINE_BRICK_PILLAR)
            .put(Blocks.DARK_PRISMARINE, ModBlocks.Pillars.DARK_PRISMARINE_PILLAR)
            .put(Blocks.SEA_LANTERN, ModBlocks.Pillars.SEA_LANTERN_PILLAR)
            .put(Blocks.TERRACOTTA, ModBlocks.Pillars.TERRACOTTA_PILLAR)
            .put(Blocks.COAL_BLOCK, ModBlocks.Pillars.COAL_PILLAR)
            .put(Blocks.PACKED_ICE, ModBlocks.Pillars.PACKED_ICE_PILLAR)
            .put(Blocks.RED_SANDSTONE, ModBlocks.Pillars.RED_SANDSTONE_PILLAR)
            .put(Blocks.CHISELED_RED_SANDSTONE, ModBlocks.Pillars.CHISELED_RED_SANDSTONE_PILLAR)
            .put(Blocks.CUT_RED_SANDSTONE, ModBlocks.Pillars.CUT_RED_SANDSTONE_PILLAR)
            .put(Blocks.MAGMA_BLOCK, ModBlocks.Pillars.MAGMA_PILLAR)
            .put(Blocks.SMOOTH_STONE, ModBlocks.Pillars.SMOOTH_STONE_PILLAR)
            .put(Blocks.SMOOTH_SANDSTONE, ModBlocks.Pillars.SMOOTH_SANDSTONE_PILLAR)
            .put(Blocks.SMOOTH_QUARTZ, ModBlocks.Pillars.SMOOTH_QUARTZ_PILLAR)
            .put(Blocks.SMOOTH_RED_SANDSTONE, ModBlocks.Pillars.SMOOTH_RED_SANDSTONE_PILLAR)
            .put(Blocks.PURPUR_BLOCK, ModBlocks.Pillars.PURPUR_PILLAR)
            .put(Blocks.PURPUR_PILLAR, ModBlocks.Pillars.PURPUR_PILLAR_PILLAR)
            .put(Blocks.ICE, ModBlocks.Pillars.ICE_PILLAR)
            .put(Blocks.END_STONE_BRICKS, ModBlocks.Pillars.END_STONE_BRICK_PILLAR)
            .put(Blocks.NETHER_WART_BLOCK, ModBlocks.Pillars.NETHER_WART_PILLAR)
            .put(Blocks.RED_NETHER_BRICKS, ModBlocks.Pillars.RED_NETHER_BRICK_PILLAR)
            .put(Blocks.BONE_BLOCK, ModBlocks.Pillars.BONE_PILLAR)
            .put(Blocks.WHITE_CONCRETE, ModBlocks.Pillars.WHITE_CONCRETE_PILLAR)
            .put(Blocks.ORANGE_CONCRETE, ModBlocks.Pillars.ORANGE_CONCRETE_PILLAR)
            .put(Blocks.MAGENTA_CONCRETE, ModBlocks.Pillars.MAGENTA_CONCRETE_PILLAR)
            .put(Blocks.LIGHT_BLUE_CONCRETE, ModBlocks.Pillars.LIGHT_BLUE_CONCRETE_PILLAR)
            .put(Blocks.YELLOW_CONCRETE, ModBlocks.Pillars.YELLOW_CONCRETE_PILLAR)
            .put(Blocks.LIME_CONCRETE, ModBlocks.Pillars.LIME_CONCRETE_PILLAR)
            .put(Blocks.PINK_CONCRETE, ModBlocks.Pillars.PINK_CONCRETE_PILLAR)
            .put(Blocks.GRAY_CONCRETE, ModBlocks.Pillars.GRAY_CONCRETE_PILLAR)
            .put(Blocks.LIGHT_GRAY_CONCRETE, ModBlocks.Pillars.LIGHT_GRAY_CONCRETE_PILLAR)
            .put(Blocks.CYAN_CONCRETE, ModBlocks.Pillars.CYAN_CONCRETE_PILLAR)
            .put(Blocks.PURPLE_CONCRETE, ModBlocks.Pillars.PURPLE_CONCRETE_PILLAR)
            .put(Blocks.BLUE_CONCRETE, ModBlocks.Pillars.BLUE_CONCRETE_PILLAR)
            .put(Blocks.BROWN_CONCRETE, ModBlocks.Pillars.BROWN_CONCRETE_PILLAR)
            .put(Blocks.GREEN_CONCRETE, ModBlocks.Pillars.GREEN_CONCRETE_PILLAR)
            .put(Blocks.RED_CONCRETE, ModBlocks.Pillars.RED_CONCRETE_PILLAR)
            .put(Blocks.BLACK_CONCRETE, ModBlocks.Pillars.BLACK_CONCRETE_PILLAR)
            .put(Blocks.DRIED_KELP_BLOCK, ModBlocks.Pillars.DRIED_KELP_PILLAR)
            .put(Blocks.DEAD_TUBE_CORAL_BLOCK, ModBlocks.Pillars.DEAD_TUBE_CORAL_PILLAR)
            .put(Blocks.DEAD_BRAIN_CORAL_BLOCK, ModBlocks.Pillars.DEAD_BRAIN_CORAL_PILLAR)
            .put(Blocks.DEAD_BUBBLE_CORAL_BLOCK, ModBlocks.Pillars.DEAD_BUBBLE_CORAL_PILLAR)
            .put(Blocks.DEAD_FIRE_CORAL_BLOCK, ModBlocks.Pillars.DEAD_FIRE_CORAL_PILLAR)
            .put(Blocks.DEAD_HORN_CORAL_BLOCK, ModBlocks.Pillars.DEAD_HORN_CORAL_PILLAR)
            .put(Blocks.TUBE_CORAL_BLOCK, ModBlocks.Pillars.TUBE_CORAL_PILLAR)
            .put(Blocks.BRAIN_CORAL_BLOCK, ModBlocks.Pillars.BRAIN_CORAL_PILLAR)
            .put(Blocks.BUBBLE_CORAL_BLOCK, ModBlocks.Pillars.BUBBLE_CORAL_PILLAR)
            .put(Blocks.FIRE_CORAL_BLOCK, ModBlocks.Pillars.FIRE_CORAL_PILLAR)
            .put(Blocks.HORN_CORAL_BLOCK, ModBlocks.Pillars.HORN_CORAL_PILLAR)
            .put(Blocks.BLUE_ICE, ModBlocks.Pillars.BLUE_ICE_PILLAR)
            .put(Blocks.REDSTONE_BLOCK, ModBlocks.Pillars.REDSTONE_PILLAR)
            .put(Blocks.TNT, ModBlocks.Pillars.TNT_PILLAR)
            .put(Blocks.WARPED_WART_BLOCK, ModBlocks.Pillars.WARPED_WART_PILLAR)
            .put(Blocks.SHROOMLIGHT, ModBlocks.Pillars.SHROOMLIGHT_PILLAR)
            .put(Blocks.CRIMSON_PLANKS, ModBlocks.Pillars.CRIMSON_PLANK_PILLAR)
            .put(Blocks.WARPED_PLANKS, ModBlocks.Pillars.WARPED_PLANK_PILLAR)
            .put(Blocks.HONEYCOMB_BLOCK, ModBlocks.Pillars.HONEYCOMB_PILLAR)
            .put(Blocks.NETHERITE_BLOCK, ModBlocks.Pillars.NETHERITE_PILLAR)
            .put(Blocks.EXPOSED_COPPER, ModBlocks.Pillars.EXPOSED_COPPER_PILLAR)
            .put(Blocks.WEATHERED_COPPER, ModBlocks.Pillars.WEATHERED_COPPER_PILLAR)
            .put(Blocks.OXIDIZED_COPPER, ModBlocks.Pillars.OXIDIZED_COPPER_PILLAR)
            .put(Blocks.CUT_COPPER, ModBlocks.Pillars.CUT_COPPER_PILLAR)
            .put(Blocks.EXPOSED_CUT_COPPER, ModBlocks.Pillars.EXPOSED_CUT_COPPER_PILLAR)
            .put(Blocks.WEATHERED_CUT_COPPER, ModBlocks.Pillars.WEATHERED_CUT_COPPER_PILLAR)
            .put(Blocks.OXIDIZED_CUT_COPPER, ModBlocks.Pillars.OXIDIZED_CUT_COPPER_PILLAR)
            .put(Blocks.ANCIENT_DEBRIS, ModBlocks.Pillars.ANCIENT_DEBRIS_PILLAR)
            .put(Blocks.LODESTONE, ModBlocks.Pillars.LODESTONE_PILLAR)
            .put(Blocks.CRYING_OBSIDIAN, ModBlocks.Pillars.CRYING_OBSIDIAN_PILLAR)
            .put(Blocks.BLACKSTONE, ModBlocks.Pillars.BLACKSTONE_PILLAR)
            .put(Blocks.POLISHED_BLACKSTONE, ModBlocks.Pillars.POLISHED_BLACKSTONE_PILLAR)
            .put(Blocks.POLISHED_BLACKSTONE_BRICKS, ModBlocks.Pillars.POLISHED_BLACKSTONE_BRICK_PILLAR)
            .put(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS, ModBlocks.Pillars.CRACKED_POLISHED_BLACKSTONE_BRICK_PILLAR)
            .put(Blocks.CHISELED_POLISHED_BLACKSTONE, ModBlocks.Pillars.CHISELED_POLISHED_BLACKSTONE_PILLAR)
            .put(Blocks.GILDED_BLACKSTONE, ModBlocks.Pillars.GILDED_BLACKSTONE_PILLAR)
            .put(Blocks.CHISELED_NETHER_BRICKS, ModBlocks.Pillars.CHISELED_NETHER_BRICK_PILLAR)
            .put(Blocks.CRACKED_NETHER_BRICKS, ModBlocks.Pillars.CRACKED_NETHER_BRICK_PILLAR)
            .put(Blocks.QUARTZ_BRICKS, ModBlocks.Pillars.QUARTZ_BRICK_PILLAR)
            .put(Blocks.QUARTZ_PILLAR, ModBlocks.Pillars.QUARTZ_PILLAR_PILLAR)
            .put(Blocks.TUFF, ModBlocks.Pillars.TUFF_PILLAR)
            .put(Blocks.CALCITE, ModBlocks.Pillars.CALCITE_PILLAR)
            .put(Blocks.WAXED_COPPER_BLOCK, ModBlocks.Pillars.WAXED_COPPER_PILLAR)
            .put(Blocks.WAXED_EXPOSED_COPPER, ModBlocks.Pillars.WAXED_EXPOSED_COPPER_PILLAR)
            .put(Blocks.WAXED_WEATHERED_COPPER, ModBlocks.Pillars.WAXED_WEATHERED_COPPER_PILLAR)
            .put(Blocks.WAXED_OXIDIZED_COPPER, ModBlocks.Pillars.WAXED_OXIDIZED_COPPER_PILLAR)
            .put(Blocks.WAXED_CUT_COPPER, ModBlocks.Pillars.WAXED_CUT_COPPER_PILLAR)
            .put(Blocks.WAXED_EXPOSED_CUT_COPPER, ModBlocks.Pillars.WAXED_EXPOSED_CUT_COPPER_PILLAR)
            .put(Blocks.WAXED_WEATHERED_CUT_COPPER, ModBlocks.Pillars.WAXED_WEATHERED_CUT_COPPER_PILLAR)
            .put(Blocks.WAXED_OXIDIZED_CUT_COPPER, ModBlocks.Pillars.WAXED_OXIDIZED_CUT_COPPER_PILLAR)
            .put(Blocks.OAK_LOG, ModBlocks.Pillars.OAK_LOG_PILLAR)
            .put(Blocks.SPRUCE_LOG, ModBlocks.Pillars.SPRUCE_LOG_PILLAR)
            .put(Blocks.BIRCH_LOG, ModBlocks.Pillars.BIRCH_LOG_PILLAR)
            .put(Blocks.JUNGLE_LOG, ModBlocks.Pillars.JUNGLE_LOG_PILLAR)
            .put(Blocks.ACACIA_LOG, ModBlocks.Pillars.ACACIA_LOG_PILLAR)
            .put(Blocks.DARK_OAK_LOG, ModBlocks.Pillars.DARK_OAK_LOG_PILLAR)
            .put(Blocks.MANGROVE_LOG, ModBlocks.Pillars.MANGROVE_LOG_PILLAR)
            .put(Blocks.CRIMSON_STEM, ModBlocks.Pillars.CRIMSON_STEM_PILLAR)
            .put(Blocks.WARPED_STEM, ModBlocks.Pillars.WARPED_STEM_PILLAR)
            .put(Blocks.STRIPPED_OAK_LOG, ModBlocks.Pillars.STRIPPED_OAK_LOG_PILLAR)
            .put(Blocks.STRIPPED_SPRUCE_LOG, ModBlocks.Pillars.STRIPPED_SPRUCE_LOG_PILLAR)
            .put(Blocks.STRIPPED_BIRCH_LOG, ModBlocks.Pillars.STRIPPED_BIRCH_LOG_PILLAR)
            .put(Blocks.STRIPPED_JUNGLE_LOG, ModBlocks.Pillars.STRIPPED_JUNGLE_LOG_PILLAR)
            .put(Blocks.STRIPPED_ACACIA_LOG, ModBlocks.Pillars.STRIPPED_ACACIA_LOG_PILLAR)
            .put(Blocks.STRIPPED_DARK_OAK_LOG, ModBlocks.Pillars.STRIPPED_DARK_OAK_LOG_PILLAR)
            .put(Blocks.STRIPPED_MANGROVE_LOG, ModBlocks.Pillars.STRIPPED_MANGROVE_LOG_PILLAR)
            .put(Blocks.STRIPPED_CRIMSON_STEM, ModBlocks.Pillars.STRIPPED_CRIMSON_STEM_PILLAR)
            .put(Blocks.STRIPPED_WARPED_STEM, ModBlocks.Pillars.STRIPPED_WARPED_STEM_PILLAR)
            .put(Blocks.STRIPPED_OAK_WOOD, ModBlocks.Pillars.STRIPPED_OAK_WOOD_PILLAR)
            .put(Blocks.STRIPPED_SPRUCE_WOOD, ModBlocks.Pillars.STRIPPED_SPRUCE_WOOD_PILLAR)
            .put(Blocks.STRIPPED_BIRCH_WOOD, ModBlocks.Pillars.STRIPPED_BIRCH_WOOD_PILLAR)
            .put(Blocks.STRIPPED_JUNGLE_WOOD, ModBlocks.Pillars.STRIPPED_JUNGLE_WOOD_PILLAR)
            .put(Blocks.STRIPPED_ACACIA_WOOD, ModBlocks.Pillars.STRIPPED_ACACIA_WOOD_PILLAR)
            .put(Blocks.STRIPPED_DARK_OAK_WOOD, ModBlocks.Pillars.STRIPPED_DARK_OAK_WOOD_PILLAR)
            .put(Blocks.STRIPPED_MANGROVE_WOOD, ModBlocks.Pillars.STRIPPED_MANGROVE_WOOD_PILLAR)
            .put(Blocks.STRIPPED_CRIMSON_HYPHAE, ModBlocks.Pillars.STRIPPED_CRIMSON_HYPHAE_PILLAR)
            .put(Blocks.STRIPPED_WARPED_HYPHAE, ModBlocks.Pillars.STRIPPED_WARPED_HYPHAE_PILLAR)
            .put(Blocks.OAK_WOOD, ModBlocks.Pillars.OAK_WOOD_PILLAR)
            .put(Blocks.SPRUCE_WOOD, ModBlocks.Pillars.SPRUCE_WOOD_PILLAR)
            .put(Blocks.BIRCH_WOOD, ModBlocks.Pillars.BIRCH_WOOD_PILLAR)
            .put(Blocks.JUNGLE_WOOD, ModBlocks.Pillars.JUNGLE_WOOD_PILLAR)
            .put(Blocks.ACACIA_WOOD, ModBlocks.Pillars.ACACIA_WOOD_PILLAR)
            .put(Blocks.DARK_OAK_WOOD, ModBlocks.Pillars.DARK_OAK_WOOD_PILLAR)
            .put(Blocks.MANGROVE_WOOD, ModBlocks.Pillars.MANGROVE_WOOD_PILLAR)
            .put(Blocks.CRIMSON_HYPHAE, ModBlocks.Pillars.CRIMSON_HYPHAE_PILLAR)
            .put(Blocks.WARPED_HYPHAE, ModBlocks.Pillars.WARPED_HYPHAE_PILLAR)
            .put(Blocks.GLASS, ModBlocks.Pillars.GLASS_PILLAR)
            .put(Blocks.TINTED_GLASS, ModBlocks.Pillars.TINTED_GLASS_PILLAR)
            .put(Blocks.DRIPSTONE_BLOCK, ModBlocks.Pillars.DRIPSTONE_PILLAR)
            .put(Blocks.COBBLED_DEEPSLATE, ModBlocks.Pillars.COBBLED_DEEPSLATE_PILLAR)
            .put(Blocks.POLISHED_DEEPSLATE, ModBlocks.Pillars.POLISHED_DEEPSLATE_PILLAR)
            .put(Blocks.DEEPSLATE_TILES, ModBlocks.Pillars.DEEPSLATE_TILE_PILLAR)
            .put(Blocks.DEEPSLATE_BRICKS, ModBlocks.Pillars.DEEPSLATE_BRICK_PILLAR)
            .put(Blocks.CHISELED_DEEPSLATE, ModBlocks.Pillars.CHISELED_DEEPSLATE_PILLAR)
            .put(Blocks.MUSHROOM_STEM, ModBlocks.Pillars.MUSHROOM_STEM_PILLAR)
            .put(Blocks.CRACKED_DEEPSLATE_BRICKS, ModBlocks.Pillars.CRACKED_DEEPSLATE_BRICK_PILLAR)
            .put(Blocks.CRACKED_DEEPSLATE_TILES, ModBlocks.Pillars.CRACKED_DEEPSLATE_TILE_PILLAR)
            .put(Blocks.SMOOTH_BASALT, ModBlocks.Pillars.SMOOTH_BASALT_PILLAR)
            .put(Blocks.RAW_IRON_BLOCK, ModBlocks.Pillars.RAW_IRON_PILLAR)
            .put(Blocks.RAW_COPPER_BLOCK, ModBlocks.Pillars.RAW_COPPER_PILLAR)
            .put(Blocks.RAW_GOLD_BLOCK, ModBlocks.Pillars.RAW_GOLD_PILLAR)
            .put(Blocks.AMETHYST_BLOCK, ModBlocks.Pillars.AMETHYST_PILLAR)
            .put(Blocks.OCHRE_FROGLIGHT, ModBlocks.Pillars.OCHRE_FROGLIGHT_PILLAR)
            .put(Blocks.VERDANT_FROGLIGHT, ModBlocks.Pillars.VERDANT_FROGLIGHT_PILLAR)
            .put(Blocks.PEARLESCENT_FROGLIGHT, ModBlocks.Pillars.PEARLESCENT_FROGLIGHT_PILLAR)
            .build();

    public ChiselItem(Settings settings) {
        super(settings);
    }

    @Override
    public ActionResult useOnBlock(ItemUsageContext context) {
        World world = context.getWorld();
        BlockPos blockPos = context.getBlockPos();
        BlockState blockState = world.getBlockState(blockPos);
        Direction side = context.getSide();
        PlayerEntity playerEntity = context.getPlayer();
        BlockState blockState2 = null;
        if (PILLAR_BLOCKS.get(blockState.getBlock()) != null) {
            blockState2 = PILLAR_BLOCKS.get(blockState.getBlock()).getDefaultState();
        }
        if (blockState2 != null) {
            world.playSound(playerEntity, blockPos, SoundEvents.BLOCK_PUMPKIN_CARVE, SoundCategory.BLOCKS, 1.0f, 1.0f);
            if (blockState.getBlock() instanceof net.minecraft.block.PillarBlock) {
                blockState2 = blockState2.with(PillarBlock.AXIS, blockState.get(PillarBlock.AXIS));
            } else {
                blockState2 = blockState2.with(PillarBlock.AXIS, side.getAxis());
            }
        }
        if (!world.isClient) {
            world.setBlockState(blockPos, blockState2, Block.NOTIFY_ALL | Block.REDRAW_ON_MAIN_THREAD);
            if (playerEntity != null) {
                context.getStack().damage(1, playerEntity, p -> p.sendToolBreakStatus(context.getHand()));
            }
        }
        return super.useOnBlock(context);
    }
}
