package net.b34tzepz.betterbuilding.datagen;

import net.b34tzepz.betterbuilding.block.ModBlocks;
import net.b34tzepz.betterbuilding.util.ModTags;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.BlockTags;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagProvider extends FabricTagProvider.BlockTagProvider {
    public ModBlockTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
        super(output, registriesFuture);
    }

    @Override
    protected void configure(RegistryWrapper.WrapperLookup wrapperLookup) {
        valueLookupBuilder(BlockTags.AXE_MINEABLE)
                .add(ModBlocks.REINFORCED_OAK_PLANKS)
                .add(ModBlocks.REINFORCED_SPRUCE_PLANKS)
                .add(ModBlocks.REINFORCED_BIRCH_PLANKS)

                .add(ModBlocks.Sides.OAK_SIDE)
                .add(ModBlocks.Sides.SPRUCE_SIDE)
                .add(ModBlocks.Sides.BIRCH_SIDE)
                .add(ModBlocks.Sides.JUNGLE_SIDE)
                .add(ModBlocks.Sides.ACACIA_SIDE)
                .add(ModBlocks.Sides.DARK_OAK_SIDE)
                .add(ModBlocks.Sides.CRIMSON_SIDE)
                .add(ModBlocks.Sides.WARPED_SIDE)

                .add(ModBlocks.Corners.OAK_CORNER)
                .add(ModBlocks.Corners.SPRUCE_CORNER)
                .add(ModBlocks.Corners.BIRCH_CORNER)
                .add(ModBlocks.Corners.JUNGLE_CORNER)
                .add(ModBlocks.Corners.ACACIA_CORNER)
                .add(ModBlocks.Corners.DARK_OAK_CORNER)
                .add(ModBlocks.Corners.CRIMSON_CORNER)
                .add(ModBlocks.Corners.WARPED_CORNER)

                .add(ModBlocks.OAK_CHAIR)
                .add(ModBlocks.SPRUCE_CHAIR)
                .add(ModBlocks.BIRCH_CHAIR)
                .add(ModBlocks.JUNGLE_CHAIR)
                .add(ModBlocks.ACACIA_CHAIR)
                .add(ModBlocks.DARK_OAK_CHAIR)
                .add(ModBlocks.CRIMSON_CHAIR)
                .add(ModBlocks.WARPED_CHAIR)

                .add(ModBlocks.OAK_TABLE);

        valueLookupBuilder(BlockTags.HOE_MINEABLE);

        valueLookupBuilder(BlockTags.PICKAXE_MINEABLE)
                .add(ModBlocks.Sides.STONE_SIDE)
                .add(ModBlocks.Sides.COBBLESTONE_SIDE)
                .add(ModBlocks.Sides.MOSSY_COBBLESTONE_SIDE)
                .add(ModBlocks.Sides.SMOOTH_STONE_SIDE)
                .add(ModBlocks.Sides.STONE_BRICK_SIDE)
                .add(ModBlocks.Sides.MOSSY_STONE_BRICK_SIDE)
                .add(ModBlocks.Sides.GRANITE_SIDE)
                .add(ModBlocks.Sides.POLISHED_GRANITE_SIDE)
                .add(ModBlocks.Sides.DIORITE_SIDE)
                .add(ModBlocks.Sides.POLISHED_DIORITE_SIDE)
                .add(ModBlocks.Sides.ANDESITE_SIDE)
                .add(ModBlocks.Sides.POLISHED_ANDESITE_SIDE)
                .add(ModBlocks.Sides.COBBLED_DEEPSLATE_SIDE)
                .add(ModBlocks.Sides.POLISHED_DEEPSLATE_SIDE)
                .add(ModBlocks.Sides.DEEPSLATE_BRICK_SIDE)
                .add(ModBlocks.Sides.DEEPSLATE_TILE_SIDE)
                .add(ModBlocks.Sides.SANDSTONE_SIDE)
                .add(ModBlocks.Sides.SMOOTH_SANDSTONE_SIDE)
                .add(ModBlocks.Sides.CUT_SANDSTONE_SIDE)
                .add(ModBlocks.Sides.RED_SANDSTONE_SIDE)
                .add(ModBlocks.Sides.SMOOTH_RED_SANDSTONE_SIDE)
                .add(ModBlocks.Sides.CUT_RED_SANDSTONE_SIDE)
                .add(ModBlocks.Sides.PRISMARINE_SIDE)
                .add(ModBlocks.Sides.PRISMARINE_BRICK_SIDE)
                .add(ModBlocks.Sides.DARK_PRISMARINE_SIDE)
                .add(ModBlocks.Sides.NETHER_BRICK_SIDE)
                .add(ModBlocks.Sides.RED_NETHER_BRICK_SIDE)
                .add(ModBlocks.Sides.BLACKSTONE_SIDE)
                .add(ModBlocks.Sides.POLISHED_BLACKSTONE_SIDE)
                .add(ModBlocks.Sides.POLISHED_BLACKSTONE_BRICK_SIDE)
                .add(ModBlocks.Sides.END_STONE_BRICK_SIDE)
                .add(ModBlocks.Sides.PURPUR_SIDE)
                .add(ModBlocks.Sides.QUARTZ_SIDE)
                .add(ModBlocks.Sides.SMOOTH_QUARTZ_SIDE)
                .add(ModBlocks.Sides.CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.EXPOSED_CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.WEATHERED_CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.OXIDIZED_CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.WAXED_CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.WAXED_EXPOSED_CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.WAXED_WEATHERED_CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.WAXED_OXIDIZED_CUT_COPPER_SIDE)

                .add(ModBlocks.SMOOTH_STONE_STAIRS)
                .add(ModBlocks.CUT_SANDSTONE_STAIRS)
                .add(ModBlocks.CUT_RED_SANDSTONE_STAIRS)

                .add(ModBlocks.Corners.STONE_CORNER)
                .add(ModBlocks.Corners.COBBLESTONE_CORNER)
                .add(ModBlocks.Corners.MOSSY_COBBLESTONE_CORNER)
                .add(ModBlocks.Corners.SMOOTH_STONE_CORNER)
                .add(ModBlocks.Corners.STONE_BRICK_CORNER)
                .add(ModBlocks.Corners.MOSSY_STONE_BRICK_CORNER)
                .add(ModBlocks.Corners.GRANITE_CORNER)
                .add(ModBlocks.Corners.POLISHED_GRANITE_CORNER)
                .add(ModBlocks.Corners.DIORITE_CORNER)
                .add(ModBlocks.Corners.POLISHED_DIORITE_CORNER)
                .add(ModBlocks.Corners.ANDESITE_CORNER)
                .add(ModBlocks.Corners.POLISHED_ANDESITE_CORNER)
                .add(ModBlocks.Corners.COBBLED_DEEPSLATE_CORNER)
                .add(ModBlocks.Corners.POLISHED_DEEPSLATE_CORNER)
                .add(ModBlocks.Corners.DEEPSLATE_BRICK_CORNER)
                .add(ModBlocks.Corners.DEEPSLATE_TILE_CORNER)
                .add(ModBlocks.Corners.SANDSTONE_CORNER)
                .add(ModBlocks.Corners.SMOOTH_SANDSTONE_CORNER)
                .add(ModBlocks.Corners.CUT_SANDSTONE_CORNER)
                .add(ModBlocks.Corners.RED_SANDSTONE_CORNER)
                .add(ModBlocks.Corners.SMOOTH_RED_SANDSTONE_CORNER)
                .add(ModBlocks.Corners.CUT_RED_SANDSTONE_CORNER)
                .add(ModBlocks.Corners.PRISMARINE_CORNER)
                .add(ModBlocks.Corners.PRISMARINE_BRICK_CORNER)
                .add(ModBlocks.Corners.DARK_PRISMARINE_CORNER)
                .add(ModBlocks.Corners.NETHER_BRICK_CORNER)
                .add(ModBlocks.Corners.RED_NETHER_BRICK_CORNER)
                .add(ModBlocks.Corners.BLACKSTONE_CORNER)
                .add(ModBlocks.Corners.POLISHED_BLACKSTONE_CORNER)
                .add(ModBlocks.Corners.POLISHED_BLACKSTONE_BRICK_CORNER)
                .add(ModBlocks.Corners.END_STONE_BRICK_CORNER)
                .add(ModBlocks.Corners.PURPUR_CORNER)
                .add(ModBlocks.Corners.QUARTZ_CORNER)
                .add(ModBlocks.Corners.SMOOTH_QUARTZ_CORNER)
                .add(ModBlocks.Corners.CUT_COPPER_CORNER)
                .add(ModBlocks.Corners.EXPOSED_CUT_COPPER_CORNER)
                .add(ModBlocks.Corners.WEATHERED_CUT_COPPER_CORNER)
                .add(ModBlocks.Corners.OXIDIZED_CUT_COPPER_CORNER)
                .add(ModBlocks.Corners.WAXED_CUT_COPPER_CORNER)
                .add(ModBlocks.Corners.WAXED_EXPOSED_CUT_COPPER_CORNER)
                .add(ModBlocks.Corners.WAXED_WEATHERED_CUT_COPPER_CORNER)
                .add(ModBlocks.Corners.WAXED_OXIDIZED_CUT_COPPER_CORNER)

                .add(ModBlocks.TELEPORTER_BLOCK);

        valueLookupBuilder(BlockTags.SHOVEL_MINEABLE);

        valueLookupBuilder(BlockTags.NEEDS_DIAMOND_TOOL);

        valueLookupBuilder(BlockTags.NEEDS_IRON_TOOL);

        valueLookupBuilder(BlockTags.NEEDS_STONE_TOOL)
                .add(ModBlocks.Sides.CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.EXPOSED_CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.WEATHERED_CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.OXIDIZED_CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.WAXED_CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.WAXED_EXPOSED_CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.WAXED_WEATHERED_CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.WAXED_OXIDIZED_CUT_COPPER_SIDE);

        valueLookupBuilder(BlockTags.STAIRS)
                .add(ModBlocks.SMOOTH_STONE_STAIRS)
                .add(ModBlocks.CUT_SANDSTONE_STAIRS)
                .add(ModBlocks.CUT_RED_SANDSTONE_STAIRS);

        valueLookupBuilder(ModTags.Blocks.SIDES)
                .addTag(ModTags.Blocks.WOODEN_SIDES)
                .add(ModBlocks.Sides.STONE_SIDE)
                .add(ModBlocks.Sides.COBBLESTONE_SIDE)
                .add(ModBlocks.Sides.MOSSY_COBBLESTONE_SIDE)
                .add(ModBlocks.Sides.SMOOTH_STONE_SIDE)
                .add(ModBlocks.Sides.STONE_BRICK_SIDE)
                .add(ModBlocks.Sides.MOSSY_STONE_BRICK_SIDE)
                .add(ModBlocks.Sides.GRANITE_SIDE)
                .add(ModBlocks.Sides.POLISHED_GRANITE_SIDE)
                .add(ModBlocks.Sides.DIORITE_SIDE)
                .add(ModBlocks.Sides.POLISHED_DIORITE_SIDE)
                .add(ModBlocks.Sides.ANDESITE_SIDE)
                .add(ModBlocks.Sides.POLISHED_ANDESITE_SIDE)
                .add(ModBlocks.Sides.COBBLED_DEEPSLATE_SIDE)
                .add(ModBlocks.Sides.POLISHED_DEEPSLATE_SIDE)
                .add(ModBlocks.Sides.DEEPSLATE_BRICK_SIDE)
                .add(ModBlocks.Sides.DEEPSLATE_TILE_SIDE)
                .add(ModBlocks.Sides.SANDSTONE_SIDE)
                .add(ModBlocks.Sides.SMOOTH_SANDSTONE_SIDE)
                .add(ModBlocks.Sides.CUT_SANDSTONE_SIDE)
                .add(ModBlocks.Sides.RED_SANDSTONE_SIDE)
                .add(ModBlocks.Sides.SMOOTH_RED_SANDSTONE_SIDE)
                .add(ModBlocks.Sides.CUT_RED_SANDSTONE_SIDE)
                .add(ModBlocks.Sides.PRISMARINE_SIDE)
                .add(ModBlocks.Sides.PRISMARINE_BRICK_SIDE)
                .add(ModBlocks.Sides.DARK_PRISMARINE_SIDE)
                .add(ModBlocks.Sides.NETHER_BRICK_SIDE)
                .add(ModBlocks.Sides.RED_NETHER_BRICK_SIDE)
                .add(ModBlocks.Sides.BLACKSTONE_SIDE)
                .add(ModBlocks.Sides.POLISHED_BLACKSTONE_SIDE)
                .add(ModBlocks.Sides.POLISHED_BLACKSTONE_BRICK_SIDE)
                .add(ModBlocks.Sides.END_STONE_BRICK_SIDE)
                .add(ModBlocks.Sides.PURPUR_SIDE)
                .add(ModBlocks.Sides.QUARTZ_SIDE)
                .add(ModBlocks.Sides.SMOOTH_QUARTZ_SIDE)
                .add(ModBlocks.Sides.CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.EXPOSED_CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.WEATHERED_CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.OXIDIZED_CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.WAXED_CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.WAXED_EXPOSED_CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.WAXED_WEATHERED_CUT_COPPER_SIDE)
                .add(ModBlocks.Sides.WAXED_OXIDIZED_CUT_COPPER_SIDE);

        valueLookupBuilder(ModTags.Blocks.WOODEN_SIDES)
                .add(ModBlocks.Sides.OAK_SIDE)
                .add(ModBlocks.Sides.SPRUCE_SIDE)
                .add(ModBlocks.Sides.BIRCH_SIDE)
                .add(ModBlocks.Sides.JUNGLE_SIDE)
                .add(ModBlocks.Sides.ACACIA_SIDE)
                .add(ModBlocks.Sides.DARK_OAK_SIDE)
                .add(ModBlocks.Sides.CRIMSON_SIDE)
                .add(ModBlocks.Sides.WARPED_SIDE);

        valueLookupBuilder(ModTags.Blocks.CORNERS)
                .addTag(ModTags.Blocks.WOODEN_CORNERS)
                .add(ModBlocks.Corners.STONE_CORNER)
                .add(ModBlocks.Corners.COBBLESTONE_CORNER)
                .add(ModBlocks.Corners.MOSSY_COBBLESTONE_CORNER)
                .add(ModBlocks.Corners.SMOOTH_STONE_CORNER)
                .add(ModBlocks.Corners.STONE_BRICK_CORNER)
                .add(ModBlocks.Corners.MOSSY_STONE_BRICK_CORNER)
                .add(ModBlocks.Corners.GRANITE_CORNER)
                .add(ModBlocks.Corners.POLISHED_GRANITE_CORNER)
                .add(ModBlocks.Corners.DIORITE_CORNER)
                .add(ModBlocks.Corners.POLISHED_DIORITE_CORNER)
                .add(ModBlocks.Corners.ANDESITE_CORNER)
                .add(ModBlocks.Corners.POLISHED_ANDESITE_CORNER)
                .add(ModBlocks.Corners.COBBLED_DEEPSLATE_CORNER)
                .add(ModBlocks.Corners.POLISHED_DEEPSLATE_CORNER)
                .add(ModBlocks.Corners.DEEPSLATE_BRICK_CORNER)
                .add(ModBlocks.Corners.DEEPSLATE_TILE_CORNER)
                .add(ModBlocks.Corners.SANDSTONE_CORNER)
                .add(ModBlocks.Corners.SMOOTH_SANDSTONE_CORNER)
                .add(ModBlocks.Corners.CUT_SANDSTONE_CORNER)
                .add(ModBlocks.Corners.RED_SANDSTONE_CORNER)
                .add(ModBlocks.Corners.SMOOTH_RED_SANDSTONE_CORNER)
                .add(ModBlocks.Corners.CUT_RED_SANDSTONE_CORNER)
                .add(ModBlocks.Corners.PRISMARINE_CORNER)
                .add(ModBlocks.Corners.PRISMARINE_BRICK_CORNER)
                .add(ModBlocks.Corners.DARK_PRISMARINE_CORNER)
                .add(ModBlocks.Corners.NETHER_BRICK_CORNER)
                .add(ModBlocks.Corners.RED_NETHER_BRICK_CORNER)
                .add(ModBlocks.Corners.BLACKSTONE_CORNER)
                .add(ModBlocks.Corners.POLISHED_BLACKSTONE_CORNER)
                .add(ModBlocks.Corners.POLISHED_BLACKSTONE_BRICK_CORNER)
                .add(ModBlocks.Corners.END_STONE_BRICK_CORNER)
                .add(ModBlocks.Corners.PURPUR_CORNER)
                .add(ModBlocks.Corners.QUARTZ_CORNER)
                .add(ModBlocks.Corners.SMOOTH_QUARTZ_CORNER)
                .add(ModBlocks.Corners.CUT_COPPER_CORNER)
                .add(ModBlocks.Corners.EXPOSED_CUT_COPPER_CORNER)
                .add(ModBlocks.Corners.WEATHERED_CUT_COPPER_CORNER)
                .add(ModBlocks.Corners.OXIDIZED_CUT_COPPER_CORNER)
                .add(ModBlocks.Corners.WAXED_CUT_COPPER_CORNER)
                .add(ModBlocks.Corners.WAXED_EXPOSED_CUT_COPPER_CORNER)
                .add(ModBlocks.Corners.WAXED_WEATHERED_CUT_COPPER_CORNER)
                .add(ModBlocks.Corners.WAXED_OXIDIZED_CUT_COPPER_CORNER);

        valueLookupBuilder(ModTags.Blocks.WOODEN_CORNERS)
                .add(ModBlocks.Corners.OAK_CORNER)
                .add(ModBlocks.Corners.SPRUCE_CORNER)
                .add(ModBlocks.Corners.BIRCH_CORNER)
                .add(ModBlocks.Corners.JUNGLE_CORNER)
                .add(ModBlocks.Corners.ACACIA_CORNER)
                .add(ModBlocks.Corners.DARK_OAK_CORNER)
                .add(ModBlocks.Corners.CRIMSON_CORNER)
                .add(ModBlocks.Corners.WARPED_CORNER);

        valueLookupBuilder(ModTags.Blocks.PILLARS);
        valueLookupBuilder(ModTags.Blocks.WOODEN_PILLARS);

    }
}
