package net.b34tzepz.betterbuilding.datagen;

import net.b34tzepz.betterbuilding.block.ModBlocks;
import net.b34tzepz.betterbuilding.block.custom.*;
import net.b34tzepz.betterbuilding.block.custom.PillarBlock;
import net.b34tzepz.betterbuilding.block.enums.SideType;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;
import net.minecraft.block.*;
import net.minecraft.block.enums.SlabType;
import net.minecraft.item.Items;
import net.minecraft.loot.LootPool;
import net.minecraft.loot.LootTable;
import net.minecraft.loot.condition.BlockStatePropertyLootCondition;
import net.minecraft.loot.condition.MatchToolLootCondition;
import net.minecraft.loot.entry.ItemEntry;
import net.minecraft.loot.entry.LootPoolEntry;
import net.minecraft.loot.function.ExplosionDecayLootFunction;
import net.minecraft.loot.function.SetCountLootFunction;
import net.minecraft.loot.provider.number.ConstantLootNumberProvider;
import net.minecraft.predicate.StatePredicate;
import net.minecraft.predicate.item.ItemPredicate;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class ModLootTableProvider extends FabricBlockLootTableProvider {
    public ModLootTableProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generate() {
        addDrop(ModBlocks.REINFORCED_OAK_PLANKS, block -> drops(block, Blocks.OAK_PLANKS));
        addDrop(ModBlocks.REINFORCED_SPRUCE_PLANKS, block -> drops(block, Blocks.SPRUCE_PLANKS));
        addDrop(ModBlocks.REINFORCED_BIRCH_PLANKS, block -> drops(block, Blocks.BIRCH_PLANKS));
        addDrop(ModBlocks.REINFORCED_JUNGLE_PLANKS, block -> drops(block, Blocks.JUNGLE_PLANKS));
        addDrop(ModBlocks.REINFORCED_ACACIA_PLANKS, block -> drops(block, Blocks.ACACIA_PLANKS));
        addDrop(ModBlocks.REINFORCED_DARK_OAK_PLANKS, block -> drops(block, Blocks.DARK_OAK_PLANKS));
        addDrop(ModBlocks.REINFORCED_MANGROVE_PLANKS, block -> drops(block, Blocks.MANGROVE_PLANKS));
        addDrop(ModBlocks.REINFORCED_CHERRY_PLANKS, block -> drops(block, Blocks.CHERRY_PLANKS));
        addDrop(ModBlocks.REINFORCED_PALE_OAK_PLANKS, block -> drops(block, Blocks.PALE_OAK_PLANKS));
        addDrop(ModBlocks.REINFORCED_BAMBOO_PLANKS, block -> drops(block, Blocks.BAMBOO_PLANKS));
        addDrop(ModBlocks.REINFORCED_BAMBOO_MOSAIC, block -> drops(block, Blocks.BAMBOO_MOSAIC));
        addDrop(ModBlocks.REINFORCED_CRIMSON_PLANKS, block -> drops(block, Blocks.CRIMSON_PLANKS));
        addDrop(ModBlocks.REINFORCED_WARPED_PLANKS, block -> drops(block, Blocks.WARPED_PLANKS));


        addSideDrop(ModBlocks.Sides.OAK_SIDE);
        addSideDrop(ModBlocks.Sides.SPRUCE_SIDE);
        addSideDrop(ModBlocks.Sides.BIRCH_SIDE);
        addSideDrop(ModBlocks.Sides.JUNGLE_SIDE);
        addSideDrop(ModBlocks.Sides.ACACIA_SIDE);
        addSideDrop(ModBlocks.Sides.DARK_OAK_SIDE);
        addSideDrop(ModBlocks.Sides.MANGROVE_SIDE);
        addSideDrop(ModBlocks.Sides.CHERRY_SIDE);
        addSideDrop(ModBlocks.Sides.PALE_OAK_SIDE);
        addSideDrop(ModBlocks.Sides.BAMBOO_SIDE);
        addSideDrop(ModBlocks.Sides.BAMBOO_MOSAIC_SIDE);
        addSideDrop(ModBlocks.Sides.CRIMSON_SIDE);
        addSideDrop(ModBlocks.Sides.WARPED_SIDE);
        addSideDrop(ModBlocks.Sides.STONE_SIDE);
        addSideDrop(ModBlocks.Sides.COBBLESTONE_SIDE);
        addSideDrop(ModBlocks.Sides.MOSSY_COBBLESTONE_SIDE);
        addSideDrop(ModBlocks.Sides.SMOOTH_STONE_SIDE);
        addSideDrop(ModBlocks.Sides.STONE_BRICK_SIDE);
        addSideDrop(ModBlocks.Sides.MOSSY_STONE_BRICK_SIDE);
        addSideDrop(ModBlocks.Sides.GRANITE_SIDE);
        addSideDrop(ModBlocks.Sides.POLISHED_GRANITE_SIDE);
        addSideDrop(ModBlocks.Sides.DIORITE_SIDE);
        addSideDrop(ModBlocks.Sides.POLISHED_DIORITE_SIDE);
        addSideDrop(ModBlocks.Sides.ANDESITE_SIDE);
        addSideDrop(ModBlocks.Sides.POLISHED_ANDESITE_SIDE);
        addSideDrop(ModBlocks.Sides.COBBLED_DEEPSLATE_SIDE);
        addSideDrop(ModBlocks.Sides.POLISHED_DEEPSLATE_SIDE);
        addSideDrop(ModBlocks.Sides.DEEPSLATE_BRICK_SIDE);
        addSideDrop(ModBlocks.Sides.DEEPSLATE_TILE_SIDE);
        addSideDrop(ModBlocks.Sides.TUFF_SIDE);
        addSideDrop(ModBlocks.Sides.POLISHED_TUFF_SIDE);
        addSideDrop(ModBlocks.Sides.TUFF_BRICK_SIDE);
        addSideDrop(ModBlocks.Sides.BRICK_SIDE);
        addSideDrop(ModBlocks.Sides.MUD_BRICK_SIDE);
        addSideDrop(ModBlocks.Sides.RESIN_BRICK_SIDE);
        addSideDrop(ModBlocks.Sides.SANDSTONE_SIDE);
        addSideDrop(ModBlocks.Sides.SMOOTH_SANDSTONE_SIDE);
        addSideDrop(ModBlocks.Sides.CUT_SANDSTONE_SIDE);
        addSideDrop(ModBlocks.Sides.RED_SANDSTONE_SIDE);
        addSideDrop(ModBlocks.Sides.SMOOTH_RED_SANDSTONE_SIDE);
        addSideDrop(ModBlocks.Sides.CUT_RED_SANDSTONE_SIDE);
        addSideDrop(ModBlocks.Sides.PRISMARINE_SIDE);
        addSideDrop(ModBlocks.Sides.PRISMARINE_BRICK_SIDE);
        addSideDrop(ModBlocks.Sides.DARK_PRISMARINE_SIDE);
        addSideDrop(ModBlocks.Sides.NETHER_BRICK_SIDE);
        addSideDrop(ModBlocks.Sides.RED_NETHER_BRICK_SIDE);
        addSideDrop(ModBlocks.Sides.BLACKSTONE_SIDE);
        addSideDrop(ModBlocks.Sides.POLISHED_BLACKSTONE_SIDE);
        addSideDrop(ModBlocks.Sides.POLISHED_BLACKSTONE_BRICK_SIDE);
        addSideDrop(ModBlocks.Sides.END_STONE_BRICK_SIDE);
        addSideDrop(ModBlocks.Sides.PURPUR_SIDE);
        addSideDrop(ModBlocks.Sides.QUARTZ_SIDE);
        addSideDrop(ModBlocks.Sides.SMOOTH_QUARTZ_SIDE);
        addSideDrop(ModBlocks.Sides.CUT_COPPER_SIDE);
        addSideDrop(ModBlocks.Sides.EXPOSED_CUT_COPPER_SIDE);
        addSideDrop(ModBlocks.Sides.WEATHERED_CUT_COPPER_SIDE);
        addSideDrop(ModBlocks.Sides.OXIDIZED_CUT_COPPER_SIDE);
        addSideDrop(ModBlocks.Sides.WAXED_CUT_COPPER_SIDE);
        addSideDrop(ModBlocks.Sides.WAXED_EXPOSED_CUT_COPPER_SIDE);
        addSideDrop(ModBlocks.Sides.WAXED_WEATHERED_CUT_COPPER_SIDE);
        addSideDrop(ModBlocks.Sides.WAXED_OXIDIZED_CUT_COPPER_SIDE);

        addDrop(ModBlocks.SMOOTH_STONE_STAIRS);
        addDrop(ModBlocks.CUT_SANDSTONE_STAIRS);
        addDrop(ModBlocks.CUT_RED_SANDSTONE_STAIRS);

        addDrop(ModBlocks.Corners.OAK_CORNER);
        addDrop(ModBlocks.Corners.SPRUCE_CORNER);
        addDrop(ModBlocks.Corners.BIRCH_CORNER);
        addDrop(ModBlocks.Corners.JUNGLE_CORNER);
        addDrop(ModBlocks.Corners.ACACIA_CORNER);
        addDrop(ModBlocks.Corners.DARK_OAK_CORNER);
        addDrop(ModBlocks.Corners.MANGROVE_CORNER);
        addDrop(ModBlocks.Corners.CHERRY_CORNER);
        addDrop(ModBlocks.Corners.PALE_OAK_CORNER);
        addDrop(ModBlocks.Corners.BAMBOO_CORNER);
        addDrop(ModBlocks.Corners.BAMBOO_MOSAIC_CORNER);
        addDrop(ModBlocks.Corners.CRIMSON_CORNER);
        addDrop(ModBlocks.Corners.WARPED_CORNER);
        addDrop(ModBlocks.Corners.STONE_CORNER);
        addDrop(ModBlocks.Corners.COBBLESTONE_CORNER);
        addDrop(ModBlocks.Corners.MOSSY_COBBLESTONE_CORNER);
        addDrop(ModBlocks.Corners.SMOOTH_STONE_CORNER);
        addDrop(ModBlocks.Corners.STONE_BRICK_CORNER);
        addDrop(ModBlocks.Corners.MOSSY_STONE_BRICK_CORNER);
        addDrop(ModBlocks.Corners.GRANITE_CORNER);
        addDrop(ModBlocks.Corners.POLISHED_GRANITE_CORNER);
        addDrop(ModBlocks.Corners.DIORITE_CORNER);
        addDrop(ModBlocks.Corners.POLISHED_DIORITE_CORNER);
        addDrop(ModBlocks.Corners.ANDESITE_CORNER);
        addDrop(ModBlocks.Corners.POLISHED_ANDESITE_CORNER);
        addDrop(ModBlocks.Corners.COBBLED_DEEPSLATE_CORNER);
        addDrop(ModBlocks.Corners.POLISHED_DEEPSLATE_CORNER);
        addDrop(ModBlocks.Corners.DEEPSLATE_BRICK_CORNER);
        addDrop(ModBlocks.Corners.DEEPSLATE_TILE_CORNER);
        addDrop(ModBlocks.Corners.TUFF_CORNER);
        addDrop(ModBlocks.Corners.POLISHED_TUFF_CORNER);
        addDrop(ModBlocks.Corners.TUFF_BRICK_CORNER);
        addDrop(ModBlocks.Corners.BRICK_CORNER);
        addDrop(ModBlocks.Corners.MUD_BRICK_CORNER);
        addDrop(ModBlocks.Corners.RESIN_BRICK_CORNER);
        addDrop(ModBlocks.Corners.SANDSTONE_CORNER);
        addDrop(ModBlocks.Corners.SMOOTH_SANDSTONE_CORNER);
        addDrop(ModBlocks.Corners.CUT_SANDSTONE_CORNER);
        addDrop(ModBlocks.Corners.RED_SANDSTONE_CORNER);
        addDrop(ModBlocks.Corners.SMOOTH_RED_SANDSTONE_CORNER);
        addDrop(ModBlocks.Corners.CUT_RED_SANDSTONE_CORNER);
        addDrop(ModBlocks.Corners.PRISMARINE_CORNER);
        addDrop(ModBlocks.Corners.PRISMARINE_BRICK_CORNER);
        addDrop(ModBlocks.Corners.DARK_PRISMARINE_CORNER);
        addDrop(ModBlocks.Corners.NETHER_BRICK_CORNER);
        addDrop(ModBlocks.Corners.RED_NETHER_BRICK_CORNER);
        addDrop(ModBlocks.Corners.BLACKSTONE_CORNER);
        addDrop(ModBlocks.Corners.POLISHED_BLACKSTONE_CORNER);
        addDrop(ModBlocks.Corners.POLISHED_BLACKSTONE_BRICK_CORNER);
        addDrop(ModBlocks.Corners.END_STONE_BRICK_CORNER);
        addDrop(ModBlocks.Corners.PURPUR_CORNER);
        addDrop(ModBlocks.Corners.QUARTZ_CORNER);
        addDrop(ModBlocks.Corners.SMOOTH_QUARTZ_CORNER);
        addDrop(ModBlocks.Corners.CUT_COPPER_CORNER);
        addDrop(ModBlocks.Corners.EXPOSED_CUT_COPPER_CORNER);
        addDrop(ModBlocks.Corners.WEATHERED_CUT_COPPER_CORNER);
        addDrop(ModBlocks.Corners.OXIDIZED_CUT_COPPER_CORNER);
        addDrop(ModBlocks.Corners.WAXED_CUT_COPPER_CORNER);
        addDrop(ModBlocks.Corners.WAXED_EXPOSED_CUT_COPPER_CORNER);
        addDrop(ModBlocks.Corners.WAXED_WEATHERED_CUT_COPPER_CORNER);
        addDrop(ModBlocks.Corners.WAXED_OXIDIZED_CUT_COPPER_CORNER);

        addDrop(ModBlocks.Pillars.OAK_LOG_PILLAR, Blocks.OAK_LOG);
        addDrop(ModBlocks.Pillars.OAK_WOOD_PILLAR, Blocks.OAK_WOOD);
        addDrop(ModBlocks.Pillars.STRIPPED_OAK_LOG_PILLAR, Blocks.STRIPPED_OAK_LOG);
        addDrop(ModBlocks.Pillars.STRIPPED_OAK_WOOD_PILLAR, Blocks.STRIPPED_OAK_WOOD);
        addDrop(ModBlocks.Pillars.OAK_PLANK_PILLAR, Blocks.OAK_PLANKS);
        addDrop(ModBlocks.Pillars.SPRUCE_LOG_PILLAR, Blocks.SPRUCE_LOG);
        addDrop(ModBlocks.Pillars.SPRUCE_WOOD_PILLAR, Blocks.SPRUCE_WOOD);
        addDrop(ModBlocks.Pillars.STRIPPED_SPRUCE_LOG_PILLAR, Blocks.STRIPPED_SPRUCE_LOG);
        addDrop(ModBlocks.Pillars.STRIPPED_SPRUCE_WOOD_PILLAR, Blocks.STRIPPED_SPRUCE_WOOD);
        addDrop(ModBlocks.Pillars.SPRUCE_PLANK_PILLAR, Blocks.SPRUCE_PLANKS);
        addDrop(ModBlocks.Pillars.BIRCH_LOG_PILLAR, Blocks.BIRCH_LOG);
        addDrop(ModBlocks.Pillars.BIRCH_WOOD_PILLAR, Blocks.BIRCH_WOOD);
        addDrop(ModBlocks.Pillars.STRIPPED_BIRCH_LOG_PILLAR, Blocks.STRIPPED_BIRCH_LOG);
        addDrop(ModBlocks.Pillars.STRIPPED_BIRCH_WOOD_PILLAR, Blocks.STRIPPED_BIRCH_WOOD);
        addDrop(ModBlocks.Pillars.BIRCH_PLANK_PILLAR, Blocks.BIRCH_PLANKS);
        addDrop(ModBlocks.Pillars.JUNGLE_LOG_PILLAR, Blocks.JUNGLE_LOG);
        addDrop(ModBlocks.Pillars.JUNGLE_WOOD_PILLAR, Blocks.JUNGLE_WOOD);
        addDrop(ModBlocks.Pillars.STRIPPED_JUNGLE_LOG_PILLAR, Blocks.STRIPPED_JUNGLE_LOG);
        addDrop(ModBlocks.Pillars.STRIPPED_JUNGLE_WOOD_PILLAR, Blocks.STRIPPED_JUNGLE_WOOD);
        addDrop(ModBlocks.Pillars.JUNGLE_PLANK_PILLAR, Blocks.JUNGLE_PLANKS);
        addDrop(ModBlocks.Pillars.ACACIA_LOG_PILLAR, Blocks.ACACIA_LOG);
        addDrop(ModBlocks.Pillars.ACACIA_WOOD_PILLAR, Blocks.ACACIA_WOOD);
        addDrop(ModBlocks.Pillars.STRIPPED_ACACIA_LOG_PILLAR, Blocks.STRIPPED_ACACIA_LOG);
        addDrop(ModBlocks.Pillars.STRIPPED_ACACIA_WOOD_PILLAR, Blocks.STRIPPED_ACACIA_WOOD);
        addDrop(ModBlocks.Pillars.ACACIA_PLANK_PILLAR, Blocks.ACACIA_PLANKS);
        addDrop(ModBlocks.Pillars.DARK_OAK_LOG_PILLAR, Blocks.DARK_OAK_LOG);
        addDrop(ModBlocks.Pillars.DARK_OAK_WOOD_PILLAR, Blocks.DARK_OAK_WOOD);
        addDrop(ModBlocks.Pillars.STRIPPED_DARK_OAK_LOG_PILLAR, Blocks.STRIPPED_DARK_OAK_LOG);
        addDrop(ModBlocks.Pillars.STRIPPED_DARK_OAK_WOOD_PILLAR, Blocks.STRIPPED_DARK_OAK_WOOD);
        addDrop(ModBlocks.Pillars.DARK_OAK_PLANK_PILLAR, Blocks.DARK_OAK_PLANKS);
        addDrop(ModBlocks.Pillars.MANGROVE_LOG_PILLAR, Blocks.MANGROVE_LOG);
        addDrop(ModBlocks.Pillars.MANGROVE_WOOD_PILLAR, Blocks.MANGROVE_WOOD);
        addDrop(ModBlocks.Pillars.STRIPPED_MANGROVE_LOG_PILLAR, Blocks.STRIPPED_MANGROVE_LOG);
        addDrop(ModBlocks.Pillars.STRIPPED_MANGROVE_WOOD_PILLAR, Blocks.STRIPPED_MANGROVE_WOOD);
        addDrop(ModBlocks.Pillars.MANGROVE_PLANK_PILLAR, Blocks.MANGROVE_PLANKS);
        addDrop(ModBlocks.Pillars.CHERRY_LOG_PILLAR, Blocks.CHERRY_LOG);
        addDrop(ModBlocks.Pillars.CHERRY_WOOD_PILLAR, Blocks.CHERRY_WOOD);
        addDrop(ModBlocks.Pillars.STRIPPED_CHERRY_LOG_PILLAR, Blocks.STRIPPED_CHERRY_LOG);
        addDrop(ModBlocks.Pillars.STRIPPED_CHERRY_WOOD_PILLAR, Blocks.STRIPPED_CHERRY_WOOD);
        addDrop(ModBlocks.Pillars.CHERRY_PLANK_PILLAR, Blocks.CHERRY_PLANKS);
        addDrop(ModBlocks.Pillars.PALE_OAK_LOG_PILLAR, Blocks.PALE_OAK_LOG);
        addDrop(ModBlocks.Pillars.PALE_OAK_WOOD_PILLAR, Blocks.PALE_OAK_WOOD);
        addDrop(ModBlocks.Pillars.STRIPPED_PALE_OAK_LOG_PILLAR, Blocks.STRIPPED_PALE_OAK_LOG);
        addDrop(ModBlocks.Pillars.STRIPPED_PALE_OAK_WOOD_PILLAR, Blocks.STRIPPED_PALE_OAK_WOOD);
        addDrop(ModBlocks.Pillars.PALE_OAK_PLANK_PILLAR, Blocks.PALE_OAK_PLANKS);
        addDrop(ModBlocks.Pillars.BAMBOO_PILLAR, Blocks.BAMBOO_BLOCK);
        addDrop(ModBlocks.Pillars.STRIPPED_BAMBOO_PILLAR, Blocks.STRIPPED_BAMBOO_BLOCK);
        addDrop(ModBlocks.Pillars.BAMBOO_PLANK_PILLAR, Blocks.BAMBOO_PLANKS);
        addDrop(ModBlocks.Pillars.BAMBOO_MOSAIC_PILLAR, Blocks.BAMBOO_MOSAIC);
        addDrop(ModBlocks.Pillars.CRIMSON_STEM_PILLAR, Blocks.CRIMSON_STEM);
        addDrop(ModBlocks.Pillars.CRIMSON_HYPHAE_PILLAR, Blocks.CRIMSON_HYPHAE);
        addDrop(ModBlocks.Pillars.STRIPPED_CRIMSON_STEM_PILLAR, Blocks.STRIPPED_CRIMSON_STEM);
        addDrop(ModBlocks.Pillars.STRIPPED_CRIMSON_HYPHAE_PILLAR, Blocks.STRIPPED_CRIMSON_HYPHAE);
        addDrop(ModBlocks.Pillars.CRIMSON_PLANK_PILLAR, Blocks.CRIMSON_PLANKS);
        addDrop(ModBlocks.Pillars.WARPED_STEM_PILLAR, Blocks.WARPED_STEM);
        addDrop(ModBlocks.Pillars.WARPED_HYPHAE_PILLAR, Blocks.WARPED_HYPHAE);
        addDrop(ModBlocks.Pillars.STRIPPED_WARPED_STEM_PILLAR, Blocks.STRIPPED_WARPED_STEM);
        addDrop(ModBlocks.Pillars.STRIPPED_WARPED_HYPHAE_PILLAR, Blocks.STRIPPED_WARPED_HYPHAE);
        addDrop(ModBlocks.Pillars.WARPED_PLANK_PILLAR, Blocks.WARPED_PLANKS);
        addDrop(ModBlocks.Pillars.STONE_PILLAR, block -> drops(Blocks.STONE, Blocks.COBBLESTONE));
        addDrop(ModBlocks.Pillars.COBBLESTONE_PILLAR, Blocks.COBBLESTONE);
        addDrop(ModBlocks.Pillars.MOSSY_COBBLESTONE_PILLAR, Blocks.MOSSY_COBBLESTONE);
        addDrop(ModBlocks.Pillars.SMOOTH_STONE_PILLAR, Blocks.SMOOTH_STONE);
        addDrop(ModBlocks.Pillars.STONE_BRICK_PILLAR, Blocks.STONE_BRICKS);
        addDrop(ModBlocks.Pillars.CRACKED_STONE_BRICK_PILLAR, Blocks.CRACKED_STONE_BRICKS);
        addDrop(ModBlocks.Pillars.CHISELED_STONE_BRICK_PILLAR, Blocks.CHISELED_STONE_BRICKS);
        addDrop(ModBlocks.Pillars.MOSSY_STONE_BRICK_PILLAR, Blocks.MOSSY_STONE_BRICKS);
        addDrop(ModBlocks.Pillars.GRANITE_PILLAR, Blocks.GRANITE);
        addDrop(ModBlocks.Pillars.POLISHED_GRANITE_PILLAR, Blocks.POLISHED_GRANITE);
        addDrop(ModBlocks.Pillars.DIORITE_PILLAR, Blocks.DIORITE);
        addDrop(ModBlocks.Pillars.POLISHED_DIORITE_PILLAR, Blocks.POLISHED_DIORITE);
        addDrop(ModBlocks.Pillars.ANDESITE_PILLAR, Blocks.ANDESITE);
        addDrop(ModBlocks.Pillars.POLISHED_ANDESITE_PILLAR, Blocks.POLISHED_ANDESITE);
        addDrop(ModBlocks.Pillars.DEEPSLATE_PILLAR, block -> drops(Blocks.DEEPSLATE, Blocks.COBBLED_DEEPSLATE));
        addDrop(ModBlocks.Pillars.COBBLED_DEEPSLATE_PILLAR, Blocks.COBBLED_DEEPSLATE);
        addDrop(ModBlocks.Pillars.CHISELED_DEEPSLATE_PILLAR, Blocks.CHISELED_DEEPSLATE);
        addDrop(ModBlocks.Pillars.POLISHED_DEEPSLATE_PILLAR, Blocks.POLISHED_DEEPSLATE);
        addDrop(ModBlocks.Pillars.DEEPSLATE_BRICK_PILLAR, Blocks.DEEPSLATE_BRICKS);
        addDrop(ModBlocks.Pillars.CRACKED_DEEPSLATE_BRICK_PILLAR, Blocks.CRACKED_DEEPSLATE_BRICKS);
        addDrop(ModBlocks.Pillars.DEEPSLATE_TILE_PILLAR, Blocks.DEEPSLATE_TILES);
        addDrop(ModBlocks.Pillars.CRACKED_DEEPSLATE_TILE_PILLAR, Blocks.CRACKED_DEEPSLATE_TILES);
        addDrop(ModBlocks.Pillars.TUFF_PILLAR, Blocks.TUFF);
        addDrop(ModBlocks.Pillars.CHISELED_TUFF_PILLAR, Blocks.CHISELED_TUFF);
        addDrop(ModBlocks.Pillars.POLISHED_TUFF_PILLAR, Blocks.POLISHED_TUFF);
        addDrop(ModBlocks.Pillars.TUFF_BRICK_PILLAR, Blocks.TUFF_BRICKS);
        addDrop(ModBlocks.Pillars.CHISELED_TUFF_BRICK_PILLAR, Blocks.CHISELED_TUFF_BRICKS);
        addDrop(ModBlocks.Pillars.BRICK_PILLAR, Blocks.BRICKS);
        addDrop(ModBlocks.Pillars.PACKED_MUD_PILLAR, Blocks.PACKED_MUD);
        addDrop(ModBlocks.Pillars.MUD_BRICK_PILLAR, Blocks.MUD_BRICKS);
        addDrop(ModBlocks.Pillars.RESIN_BRICK_PILLAR, Blocks.RESIN_BRICKS);
        addDrop(ModBlocks.Pillars.CHISELED_RESIN_BRICK_PILLAR, Blocks.CHISELED_RESIN_BRICKS);
        addDrop(ModBlocks.Pillars.SANDSTONE_PILLAR, Blocks.SANDSTONE);
        addDrop(ModBlocks.Pillars.CHISELED_SANDSTONE_PILLAR, Blocks.CHISELED_SANDSTONE);
        addDrop(ModBlocks.Pillars.SMOOTH_SANDSTONE_PILLAR, Blocks.SMOOTH_SANDSTONE);
        addDrop(ModBlocks.Pillars.CUT_SANDSTONE_PILLAR, Blocks.CUT_SANDSTONE);
        addDrop(ModBlocks.Pillars.RED_SANDSTONE_PILLAR, Blocks.RED_SANDSTONE);
        addDrop(ModBlocks.Pillars.CHISELED_RED_SANDSTONE_PILLAR, Blocks.CHISELED_RED_SANDSTONE);
        addDrop(ModBlocks.Pillars.SMOOTH_RED_SANDSTONE_PILLAR, Blocks.SMOOTH_RED_SANDSTONE);
        addDrop(ModBlocks.Pillars.CUT_RED_SANDSTONE_PILLAR, Blocks.CUT_RED_SANDSTONE);
        addDrop(ModBlocks.Pillars.SEA_LANTERN_PILLAR, block -> this.dropsWithSilkTouch(Blocks.SEA_LANTERN));
        addDrop(ModBlocks.Pillars.PRISMARINE_PILLAR, Blocks.PRISMARINE);
        addDrop(ModBlocks.Pillars.PRISMARINE_BRICK_PILLAR, Blocks.PRISMARINE_BRICKS);
        addDrop(ModBlocks.Pillars.DARK_PRISMARINE_PILLAR, Blocks.DARK_PRISMARINE);
        addDrop(ModBlocks.Pillars.NETHERRACK_PILLAR, Blocks.NETHERRACK);
        addDrop(ModBlocks.Pillars.NETHER_BRICK_PILLAR, Blocks.NETHER_BRICKS);
        addDrop(ModBlocks.Pillars.CRACKED_NETHER_BRICK_PILLAR, Blocks.CRACKED_NETHER_BRICKS);
        addDrop(ModBlocks.Pillars.CHISELED_NETHER_BRICK_PILLAR, Blocks.CHISELED_NETHER_BRICKS);
        addDrop(ModBlocks.Pillars.RED_NETHER_BRICK_PILLAR, Blocks.RED_NETHER_BRICKS);
        addDrop(ModBlocks.Pillars.BASALT_PILLAR, Blocks.BASALT);
        addDrop(ModBlocks.Pillars.SMOOTH_BASALT_PILLAR, Blocks.SMOOTH_BASALT);
        addDrop(ModBlocks.Pillars.POLISHED_BASALT_PILLAR, Blocks.POLISHED_BASALT);
        addDrop(ModBlocks.Pillars.BLACKSTONE_PILLAR, Blocks.BLACKSTONE);
        addDrop(ModBlocks.Pillars.GILDED_BLACKSTONE_PILLAR, Blocks.GILDED_BLACKSTONE);
        addDrop(ModBlocks.Pillars.CHISELED_POLISHED_BLACKSTONE_PILLAR, Blocks.CHISELED_POLISHED_BLACKSTONE);
        addDrop(ModBlocks.Pillars.POLISHED_BLACKSTONE_PILLAR, Blocks.POLISHED_BLACKSTONE);
        addDrop(ModBlocks.Pillars.POLISHED_BLACKSTONE_BRICK_PILLAR, Blocks.POLISHED_BLACKSTONE_BRICKS);
        addDrop(ModBlocks.Pillars.CRACKED_POLISHED_BLACKSTONE_BRICK_PILLAR, Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS);
        addDrop(ModBlocks.Pillars.END_STONE_PILLAR, Blocks.END_STONE);
        addDrop(ModBlocks.Pillars.END_STONE_BRICK_PILLAR, Blocks.END_STONE_BRICKS);
        addDrop(ModBlocks.Pillars.PURPUR_PILLAR, Blocks.PURPUR_BLOCK);
        addDrop(ModBlocks.Pillars.PURPUR_PILLAR_PILLAR, Blocks.PURPUR_PILLAR);
        addDrop(ModBlocks.Pillars.COAL_PILLAR, Blocks.COAL_BLOCK);
        addDrop(ModBlocks.Pillars.IRON_PILLAR, Blocks.IRON_BLOCK);
        addDrop(ModBlocks.Pillars.GOLD_PILLAR, Blocks.GOLD_BLOCK);
        addDrop(ModBlocks.Pillars.REDSTONE_PILLAR, Blocks.REDSTONE_BLOCK);
        addDrop(ModBlocks.Pillars.LAPIS_PILLAR, Blocks.LAPIS_BLOCK);
        addDrop(ModBlocks.Pillars.EMERALD_PILLAR, Blocks.EMERALD_BLOCK);
        addDrop(ModBlocks.Pillars.DIAMOND_PILLAR, Blocks.DIAMOND_BLOCK);
        addDrop(ModBlocks.Pillars.NETHERITE_PILLAR, Blocks.NETHERITE_BLOCK);
        addDrop(ModBlocks.Pillars.QUARTZ_PILLAR, Blocks.QUARTZ_BLOCK);
        addDrop(ModBlocks.Pillars.CHISELED_QUARTZ_PILLAR, Blocks.CHISELED_QUARTZ_BLOCK);
        addDrop(ModBlocks.Pillars.QUARTZ_BRICK_PILLAR, Blocks.QUARTZ_BRICKS);
        addDrop(ModBlocks.Pillars.QUARTZ_PILLAR_PILLAR, Blocks.QUARTZ_PILLAR);
        addDrop(ModBlocks.Pillars.SMOOTH_QUARTZ_PILLAR, Blocks.SMOOTH_QUARTZ);
        addDrop(ModBlocks.Pillars.AMETHYST_PILLAR, Blocks.AMETHYST_BLOCK);
        addDrop(ModBlocks.Pillars.COPPER_PILLAR, Blocks.COPPER_BLOCK);
        addDrop(ModBlocks.Pillars.CHISELED_COPPER_PILLAR, Blocks.CHISELED_COPPER);
        addDrop(ModBlocks.Pillars.COPPER_GRATE_PILLAR, Blocks.COPPER_GRATE);
        addDrop(ModBlocks.Pillars.CUT_COPPER_PILLAR, Blocks.CUT_COPPER);
        addDrop(ModBlocks.Pillars.COPPER_BULB_PILLAR, Blocks.COPPER_BULB);
        addDrop(ModBlocks.Pillars.EXPOSED_COPPER_PILLAR, Blocks.EXPOSED_COPPER);
        addDrop(ModBlocks.Pillars.EXPOSED_CHISELED_COPPER_PILLAR, Blocks.EXPOSED_CHISELED_COPPER);
        addDrop(ModBlocks.Pillars.EXPOSED_COPPER_GRATE_PILLAR, Blocks.EXPOSED_COPPER_GRATE);
        addDrop(ModBlocks.Pillars.EXPOSED_CUT_COPPER_PILLAR, Blocks.EXPOSED_CUT_COPPER);
        addDrop(ModBlocks.Pillars.EXPOSED_COPPER_BULB_PILLAR, Blocks.EXPOSED_COPPER_BULB);
        addDrop(ModBlocks.Pillars.WEATHERED_COPPER_PILLAR, Blocks.WEATHERED_COPPER);
        addDrop(ModBlocks.Pillars.WEATHERED_CHISELED_COPPER_PILLAR, Blocks.WEATHERED_CHISELED_COPPER);
        addDrop(ModBlocks.Pillars.WEATHERED_COPPER_GRATE_PILLAR, Blocks.WEATHERED_COPPER_GRATE);
        addDrop(ModBlocks.Pillars.WEATHERED_CUT_COPPER_PILLAR, Blocks.WEATHERED_CUT_COPPER);
        addDrop(ModBlocks.Pillars.WEATHERED_COPPER_BULB_PILLAR, Blocks.WEATHERED_COPPER_BULB);
        addDrop(ModBlocks.Pillars.OXIDIZED_COPPER_PILLAR, Blocks.OXIDIZED_COPPER);
        addDrop(ModBlocks.Pillars.OXIDIZED_CHISELED_COPPER_PILLAR, Blocks.OXIDIZED_CHISELED_COPPER);
        addDrop(ModBlocks.Pillars.OXIDIZED_COPPER_GRATE_PILLAR, Blocks.OXIDIZED_COPPER_GRATE);
        addDrop(ModBlocks.Pillars.OXIDIZED_CUT_COPPER_PILLAR, Blocks.OXIDIZED_CUT_COPPER);
        addDrop(ModBlocks.Pillars.OXIDIZED_COPPER_BULB_PILLAR, Blocks.OXIDIZED_COPPER_BULB);
        addDrop(ModBlocks.Pillars.WAXED_COPPER_PILLAR, Blocks.WAXED_COPPER_BLOCK);
        addDrop(ModBlocks.Pillars.WAXED_CHISELED_COPPER_PILLAR, Blocks.WAXED_CHISELED_COPPER);
        addDrop(ModBlocks.Pillars.WAXED_COPPER_GRATE_PILLAR, Blocks.WAXED_COPPER_GRATE);
        addDrop(ModBlocks.Pillars.WAXED_CUT_COPPER_PILLAR, Blocks.WAXED_CUT_COPPER);
        addDrop(ModBlocks.Pillars.WAXED_COPPER_BULB_PILLAR, Blocks.WAXED_COPPER_BULB);
        addDrop(ModBlocks.Pillars.WAXED_EXPOSED_COPPER_PILLAR, Blocks.WAXED_EXPOSED_COPPER);
        addDrop(ModBlocks.Pillars.WAXED_EXPOSED_CHISELED_COPPER_PILLAR, Blocks.WAXED_EXPOSED_CHISELED_COPPER);
        addDrop(ModBlocks.Pillars.WAXED_EXPOSED_COPPER_GRATE_PILLAR, Blocks.WAXED_EXPOSED_COPPER_GRATE);
        addDrop(ModBlocks.Pillars.WAXED_EXPOSED_CUT_COPPER_PILLAR, Blocks.WAXED_EXPOSED_CUT_COPPER);
        addDrop(ModBlocks.Pillars.WAXED_EXPOSED_COPPER_BULB_PILLAR, Blocks.WAXED_EXPOSED_COPPER_BULB);
        addDrop(ModBlocks.Pillars.WAXED_WEATHERED_COPPER_PILLAR, Blocks.WAXED_WEATHERED_COPPER);
        addDrop(ModBlocks.Pillars.WAXED_WEATHERED_CHISELED_COPPER_PILLAR, Blocks.WAXED_WEATHERED_CHISELED_COPPER);
        addDrop(ModBlocks.Pillars.WAXED_WEATHERED_COPPER_GRATE_PILLAR, Blocks.WAXED_WEATHERED_COPPER_GRATE);
        addDrop(ModBlocks.Pillars.WAXED_WEATHERED_CUT_COPPER_PILLAR, Blocks.WAXED_WEATHERED_CUT_COPPER);
        addDrop(ModBlocks.Pillars.WAXED_WEATHERED_COPPER_BULB_PILLAR, Blocks.WAXED_WEATHERED_COPPER_BULB);
        addDrop(ModBlocks.Pillars.WAXED_OXIDIZED_COPPER_PILLAR, Blocks.WAXED_OXIDIZED_COPPER);
        addDrop(ModBlocks.Pillars.WAXED_OXIDIZED_CHISELED_COPPER_PILLAR, Blocks.WAXED_OXIDIZED_CHISELED_COPPER);
        addDrop(ModBlocks.Pillars.WAXED_OXIDIZED_COPPER_GRATE_PILLAR, Blocks.WAXED_OXIDIZED_COPPER_GRATE);
        addDrop(ModBlocks.Pillars.WAXED_OXIDIZED_CUT_COPPER_PILLAR, Blocks.WAXED_OXIDIZED_CUT_COPPER);
        addDrop(ModBlocks.Pillars.WAXED_OXIDIZED_COPPER_BULB_PILLAR, Blocks.WAXED_OXIDIZED_COPPER_BULB);
        addDrop(ModBlocks.Pillars.WHITE_WOOL_PILLAR, Blocks.WHITE_WOOL);
        addDrop(ModBlocks.Pillars.LIGHT_GRAY_WOOL_PILLAR, Blocks.LIGHT_GRAY_WOOL);
        addDrop(ModBlocks.Pillars.GRAY_WOOL_PILLAR, Blocks.GRAY_WOOL);
        addDrop(ModBlocks.Pillars.BLACK_WOOL_PILLAR, Blocks.BLACK_WOOL);
        addDrop(ModBlocks.Pillars.BROWN_WOOL_PILLAR, Blocks.BROWN_WOOL);
        addDrop(ModBlocks.Pillars.RED_WOOL_PILLAR, Blocks.RED_WOOL);
        addDrop(ModBlocks.Pillars.ORANGE_WOOL_PILLAR, Blocks.ORANGE_WOOL);
        addDrop(ModBlocks.Pillars.YELLOW_WOOL_PILLAR, Blocks.YELLOW_WOOL);
        addDrop(ModBlocks.Pillars.LIME_WOOL_PILLAR, Blocks.LIME_WOOL);
        addDrop(ModBlocks.Pillars.GREEN_WOOL_PILLAR, Blocks.GREEN_WOOL);
        addDrop(ModBlocks.Pillars.CYAN_WOOL_PILLAR, Blocks.CYAN_WOOL);
        addDrop(ModBlocks.Pillars.LIGHT_BLUE_WOOL_PILLAR, Blocks.LIGHT_BLUE_WOOL);
        addDrop(ModBlocks.Pillars.BLUE_WOOL_PILLAR, Blocks.BLUE_WOOL);
        addDrop(ModBlocks.Pillars.PURPLE_WOOL_PILLAR, Blocks.PURPLE_WOOL);
        addDrop(ModBlocks.Pillars.MAGENTA_WOOL_PILLAR, Blocks.MAGENTA_WOOL);
        addDrop(ModBlocks.Pillars.PINK_WOOL_PILLAR, Blocks.PINK_WOOL);
        addDrop(ModBlocks.Pillars.TERRACOTTA_PILLAR, Blocks.TERRACOTTA);
        addDrop(ModBlocks.Pillars.WHITE_TERRACOTTA_PILLAR, Blocks.WHITE_TERRACOTTA);
        addDrop(ModBlocks.Pillars.LIGHT_GRAY_TERRACOTTA_PILLAR, Blocks.LIGHT_GRAY_TERRACOTTA);
        addDrop(ModBlocks.Pillars.GRAY_TERRACOTTA_PILLAR, Blocks.GRAY_TERRACOTTA);
        addDrop(ModBlocks.Pillars.BLACK_TERRACOTTA_PILLAR, Blocks.BLACK_TERRACOTTA);
        addDrop(ModBlocks.Pillars.BROWN_TERRACOTTA_PILLAR, Blocks.BROWN_TERRACOTTA);
        addDrop(ModBlocks.Pillars.RED_TERRACOTTA_PILLAR, Blocks.RED_TERRACOTTA);
        addDrop(ModBlocks.Pillars.ORANGE_TERRACOTTA_PILLAR, Blocks.ORANGE_TERRACOTTA);
        addDrop(ModBlocks.Pillars.YELLOW_TERRACOTTA_PILLAR, Blocks.YELLOW_TERRACOTTA);
        addDrop(ModBlocks.Pillars.LIME_TERRACOTTA_PILLAR, Blocks.LIME_TERRACOTTA);
        addDrop(ModBlocks.Pillars.GREEN_TERRACOTTA_PILLAR, Blocks.GREEN_TERRACOTTA);
        addDrop(ModBlocks.Pillars.CYAN_TERRACOTTA_PILLAR, Blocks.CYAN_TERRACOTTA);
        addDrop(ModBlocks.Pillars.LIGHT_BLUE_TERRACOTTA_PILLAR, Blocks.LIGHT_BLUE_TERRACOTTA);
        addDrop(ModBlocks.Pillars.BLUE_TERRACOTTA_PILLAR, Blocks.BLUE_TERRACOTTA);
        addDrop(ModBlocks.Pillars.PURPLE_TERRACOTTA_PILLAR, Blocks.PURPLE_TERRACOTTA);
        addDrop(ModBlocks.Pillars.MAGENTA_TERRACOTTA_PILLAR, Blocks.MAGENTA_TERRACOTTA);
        addDrop(ModBlocks.Pillars.PINK_TERRACOTTA_PILLAR, Blocks.PINK_TERRACOTTA);
        addDrop(ModBlocks.Pillars.WHITE_CONCRETE_PILLAR, Blocks.WHITE_CONCRETE);
        addDrop(ModBlocks.Pillars.LIGHT_GRAY_CONCRETE_PILLAR, Blocks.LIGHT_GRAY_CONCRETE);
        addDrop(ModBlocks.Pillars.GRAY_CONCRETE_PILLAR, Blocks.GRAY_CONCRETE);
        addDrop(ModBlocks.Pillars.BLACK_CONCRETE_PILLAR, Blocks.BLACK_CONCRETE);
        addDrop(ModBlocks.Pillars.BROWN_CONCRETE_PILLAR, Blocks.BROWN_CONCRETE);
        addDrop(ModBlocks.Pillars.RED_CONCRETE_PILLAR, Blocks.RED_CONCRETE);
        addDrop(ModBlocks.Pillars.ORANGE_CONCRETE_PILLAR, Blocks.ORANGE_CONCRETE);
        addDrop(ModBlocks.Pillars.YELLOW_CONCRETE_PILLAR, Blocks.YELLOW_CONCRETE);
        addDrop(ModBlocks.Pillars.LIME_CONCRETE_PILLAR, Blocks.LIME_CONCRETE);
        addDrop(ModBlocks.Pillars.GREEN_CONCRETE_PILLAR, Blocks.GREEN_CONCRETE);
        addDrop(ModBlocks.Pillars.CYAN_CONCRETE_PILLAR, Blocks.CYAN_CONCRETE);
        addDrop(ModBlocks.Pillars.LIGHT_BLUE_CONCRETE_PILLAR, Blocks.LIGHT_BLUE_CONCRETE);
        addDrop(ModBlocks.Pillars.BLUE_CONCRETE_PILLAR, Blocks.BLUE_CONCRETE);
        addDrop(ModBlocks.Pillars.PURPLE_CONCRETE_PILLAR, Blocks.PURPLE_CONCRETE);
        addDrop(ModBlocks.Pillars.MAGENTA_CONCRETE_PILLAR, Blocks.MAGENTA_CONCRETE);
        addDrop(ModBlocks.Pillars.PINK_CONCRETE_PILLAR, Blocks.PINK_CONCRETE);
        addDrop(ModBlocks.Pillars.GLASS_PILLAR, block -> this.dropsWithSilkTouch(Blocks.GLASS));
        addDrop(ModBlocks.Pillars.WHITE_STAINED_GLASS_PILLAR, block -> this.dropsWithSilkTouch(Blocks.WHITE_STAINED_GLASS));
        addDrop(ModBlocks.Pillars.LIGHT_GRAY_STAINED_GLASS_PILLAR, block -> this.dropsWithSilkTouch(Blocks.LIGHT_GRAY_STAINED_GLASS));
        addDrop(ModBlocks.Pillars.GRAY_STAINED_GLASS_PILLAR, block -> this.dropsWithSilkTouch(Blocks.GRAY_STAINED_GLASS));
        addDrop(ModBlocks.Pillars.BLACK_STAINED_GLASS_PILLAR, block -> this.dropsWithSilkTouch(Blocks.BLACK_STAINED_GLASS));
        addDrop(ModBlocks.Pillars.BROWN_STAINED_GLASS_PILLAR, block -> this.dropsWithSilkTouch(Blocks.BROWN_STAINED_GLASS));
        addDrop(ModBlocks.Pillars.RED_STAINED_GLASS_PILLAR, block -> this.dropsWithSilkTouch(Blocks.RED_STAINED_GLASS));
        addDrop(ModBlocks.Pillars.ORANGE_STAINED_GLASS_PILLAR, block -> this.dropsWithSilkTouch(Blocks.ORANGE_STAINED_GLASS));
        addDrop(ModBlocks.Pillars.YELLOW_STAINED_GLASS_PILLAR, block -> this.dropsWithSilkTouch(Blocks.YELLOW_STAINED_GLASS));
        addDrop(ModBlocks.Pillars.LIME_STAINED_GLASS_PILLAR, block -> this.dropsWithSilkTouch(Blocks.LIME_STAINED_GLASS));
        addDrop(ModBlocks.Pillars.GREEN_STAINED_GLASS_PILLAR, block -> this.dropsWithSilkTouch(Blocks.GREEN_STAINED_GLASS));
        addDrop(ModBlocks.Pillars.CYAN_STAINED_GLASS_PILLAR, block -> this.dropsWithSilkTouch(Blocks.CYAN_STAINED_GLASS));
        addDrop(ModBlocks.Pillars.LIGHT_BLUE_STAINED_GLASS_PILLAR, block -> this.dropsWithSilkTouch(Blocks.LIGHT_BLUE_STAINED_GLASS));
        addDrop(ModBlocks.Pillars.BLUE_STAINED_GLASS_PILLAR, block -> this.dropsWithSilkTouch(Blocks.BLUE_STAINED_GLASS));
        addDrop(ModBlocks.Pillars.PURPLE_STAINED_GLASS_PILLAR, block -> this.dropsWithSilkTouch(Blocks.PURPLE_STAINED_GLASS));
        addDrop(ModBlocks.Pillars.MAGENTA_STAINED_GLASS_PILLAR, block -> this.dropsWithSilkTouch(Blocks.MAGENTA_STAINED_GLASS));
        addDrop(ModBlocks.Pillars.PINK_STAINED_GLASS_PILLAR, block -> this.dropsWithSilkTouch(Blocks.PINK_STAINED_GLASS));
        addDrop(ModBlocks.Pillars.PODZOL_PILLAR, block -> drops(Blocks.PODZOL, Blocks.DIRT));
        addDrop(ModBlocks.Pillars.MYCELIUM_PILLAR, block -> drops(Blocks.MYCELIUM, Blocks.DIRT));
        addDrop(ModBlocks.Pillars.DIRT_PILLAR, Blocks.DIRT);
        addDrop(ModBlocks.Pillars.COARSE_DIRT_PILLAR, Blocks.COARSE_DIRT);
        addDrop(ModBlocks.Pillars.ROOTED_DIRT_PILLAR, Blocks.ROOTED_DIRT);
        addDrop(ModBlocks.Pillars.MUD_PILLAR, Blocks.MUD);
        addDrop(ModBlocks.Pillars.CLAY_PILLAR, Blocks.CLAY);
        this.addDrop(ModBlocks.Pillars.CLAY_PILLAR, block -> this.drops(Blocks.CLAY, Items.CLAY_BALL, ConstantLootNumberProvider.create(4.0F)));
        addDrop(ModBlocks.Pillars.ICE_PILLAR, block -> this.dropsWithSilkTouch(Blocks.ICE));
        addDrop(ModBlocks.Pillars.PACKED_ICE_PILLAR, block -> this.dropsWithSilkTouch(Blocks.PACKED_ICE));
        addDrop(ModBlocks.Pillars.BLUE_ICE_PILLAR, block -> this.dropsWithSilkTouch(Blocks.BLUE_ICE));
        addDrop(ModBlocks.Pillars.SNOW_PILLAR, Blocks.SNOW_BLOCK);
        this.addDrop(ModBlocks.Pillars.SNOW_PILLAR, block -> this.drops(Blocks.SNOW_BLOCK, Items.SNOWBALL, ConstantLootNumberProvider.create(4.0F)));
        addDrop(ModBlocks.Pillars.MOSS_PILLAR, Blocks.MOSS_BLOCK);
        addDrop(ModBlocks.Pillars.PALE_MOSS_PILLAR, Blocks.PALE_MOSS_BLOCK);
        addDrop(ModBlocks.Pillars.CALCITE_PILLAR, Blocks.CALCITE);
        addDrop(ModBlocks.Pillars.DRIPSTONE_PILLAR, Blocks.DRIPSTONE_BLOCK);
        addDrop(ModBlocks.Pillars.MAGMA_PILLAR, Blocks.MAGMA_BLOCK);
        addDrop(ModBlocks.Pillars.OBSIDIAN_PILLAR, Blocks.OBSIDIAN);
        addDrop(ModBlocks.Pillars.CRYING_OBSIDIAN_PILLAR, Blocks.CRYING_OBSIDIAN);
        this.addDrop(ModBlocks.Pillars.CRIMSON_NYLIUM_PILLAR, block -> this.drops(Blocks.CRIMSON_NYLIUM, Blocks.NETHERRACK));
        this.addDrop(ModBlocks.Pillars.WARPED_NYLIUM_PILLAR, block -> this.drops(Blocks.WARPED_NYLIUM, Blocks.NETHERRACK));
        addDrop(ModBlocks.Pillars.SOUL_SAND_PILLAR, Blocks.SOUL_SAND);
        addDrop(ModBlocks.Pillars.SOUL_SOIL_PILLAR, Blocks.SOUL_SOIL);
        addDrop(ModBlocks.Pillars.BONE_PILLAR, Blocks.BONE_BLOCK);
        addDrop(ModBlocks.Pillars.GLOWSTONE_PILLAR, block -> this.dropsWithSilkTouch(Blocks.GLOWSTONE));
        addDrop(ModBlocks.Pillars.MUDDY_MANGROVE_ROOT_PILLAR, Blocks.MUDDY_MANGROVE_ROOTS);
        addDrop(ModBlocks.Pillars.MUSHROOM_STEM_PILLAR, block -> this.dropsWithSilkTouch(Blocks.MUSHROOM_STEM));
        this.addDrop(ModBlocks.Pillars.BROWN_MUSHROOM_PILLAR, block -> this.drops(Blocks.BROWN_MUSHROOM_BLOCK, Blocks.BROWN_MUSHROOM));
        this.addDrop(ModBlocks.Pillars.RED_MUSHROOM_PILLAR, block -> this.drops(Blocks.RED_MUSHROOM_BLOCK, Blocks.RED_MUSHROOM));
        addDrop(ModBlocks.Pillars.NETHER_WART_PILLAR, Blocks.NETHER_WART_BLOCK);
        addDrop(ModBlocks.Pillars.WARPED_WART_PILLAR, Blocks.WARPED_WART_BLOCK);
        addDrop(ModBlocks.Pillars.SHROOMLIGHT_PILLAR, Blocks.SHROOMLIGHT);
        this.addDrop(ModBlocks.Pillars.TUBE_CORAL_PILLAR, block -> this.drops(Blocks.TUBE_CORAL_BLOCK, Blocks.DEAD_TUBE_CORAL_BLOCK));
        this.addDrop(ModBlocks.Pillars.BRAIN_CORAL_PILLAR, block -> this.drops(Blocks.BRAIN_CORAL_BLOCK, Blocks.DEAD_BRAIN_CORAL_BLOCK));
        this.addDrop(ModBlocks.Pillars.BUBBLE_CORAL_PILLAR, block -> this.drops(Blocks.BUBBLE_CORAL_BLOCK, Blocks.DEAD_BUBBLE_CORAL_BLOCK));
        this.addDrop(ModBlocks.Pillars.FIRE_CORAL_PILLAR, block -> this.drops(Blocks.FIRE_CORAL_BLOCK, Blocks.DEAD_FIRE_CORAL_BLOCK));
        this.addDrop(ModBlocks.Pillars.HORN_CORAL_PILLAR, block -> this.drops(Blocks.HORN_CORAL_BLOCK, Blocks.DEAD_HORN_CORAL_BLOCK));
        addDrop(ModBlocks.Pillars.DEAD_TUBE_CORAL_PILLAR, Blocks.DEAD_TUBE_CORAL_BLOCK);
        addDrop(ModBlocks.Pillars.DEAD_BRAIN_CORAL_PILLAR, Blocks.DEAD_BRAIN_CORAL_BLOCK);
        addDrop(ModBlocks.Pillars.DEAD_BUBBLE_CORAL_PILLAR, Blocks.DEAD_BUBBLE_CORAL_BLOCK);
        addDrop(ModBlocks.Pillars.DEAD_FIRE_CORAL_PILLAR, Blocks.DEAD_FIRE_CORAL_BLOCK);
        addDrop(ModBlocks.Pillars.DEAD_HORN_CORAL_PILLAR, Blocks.DEAD_HORN_CORAL_BLOCK);
        addDrop(ModBlocks.Pillars.SPONGE_PILLAR, Blocks.SPONGE);
        addDrop(ModBlocks.Pillars.WET_SPONGE_PILLAR, Blocks.WET_SPONGE);
        addDrop(ModBlocks.Pillars.HAY_PILLAR, Blocks.HAY_BLOCK);
        addDrop(ModBlocks.Pillars.HONEYCOMB_PILLAR, Blocks.HONEYCOMB_BLOCK);
        addDrop(ModBlocks.Pillars.SLIME_PILLAR, Blocks.SLIME_BLOCK);
        addDrop(ModBlocks.Pillars.HONEY_PILLAR, Blocks.HONEY_BLOCK);
        addDrop(ModBlocks.Pillars.RESIN_PILLAR, Blocks.RESIN_BLOCK);
        addDrop(ModBlocks.Pillars.OCHRE_FROGLIGHT_PILLAR, Blocks.OCHRE_FROGLIGHT);
        addDrop(ModBlocks.Pillars.VERDANT_FROGLIGHT_PILLAR, Blocks.VERDANT_FROGLIGHT);
        addDrop(ModBlocks.Pillars.PEARLESCENT_FROGLIGHT_PILLAR, Blocks.PEARLESCENT_FROGLIGHT);
        addDrop(ModBlocks.Pillars.SCULK_PILLAR, block -> this.dropsWithSilkTouch(Blocks.SCULK));
//        addDrop(ModBlocks.Pillars.SCULK_CATALYST_PILLAR, block -> this.dropsWithSilkTouch(Blocks.SCULK_CATALYST));
        addDrop(ModBlocks.Pillars.LODESTONE_PILLAR, Blocks.LODESTONE);
        this.addDrop(ModBlocks.Pillars.BOOKSHELF_PILLAR, block -> this.drops(Blocks.BOOKSHELF, Items.BOOK, ConstantLootNumberProvider.create(3.0F)));
//        addDrop(ModBlocks.Pillars.CHISELED_BOOKSHELF_PILLAR, block -> this.dropsWithSilkTouch(Blocks.CHISELED_BOOKSHELF));
        addDrop(ModBlocks.Pillars.TARGET_PILLAR, Blocks.TARGET);
        addDrop(ModBlocks.Pillars.TNT_PILLAR, Blocks.TNT);
//        addDrop(ModBlocks.Pillars.CREAKING_HEART_PILLAR, block -> this.dropsWithSilkTouch(Blocks.CREAKING_HEART));

        addDrop(ModBlocks.OAK_CHAIR);
        addDrop(ModBlocks.SPRUCE_CHAIR);
        addDrop(ModBlocks.BIRCH_CHAIR);
        addDrop(ModBlocks.JUNGLE_CHAIR);
        addDrop(ModBlocks.ACACIA_CHAIR);
        addDrop(ModBlocks.DARK_OAK_CHAIR);
        addDrop(ModBlocks.MANGROVE_CHAIR);
        addDrop(ModBlocks.CHERRY_CHAIR);
        addDrop(ModBlocks.PALE_OAK_CHAIR);
        addDrop(ModBlocks.BAMBOO_CHAIR);
        addDrop(ModBlocks.BAMBOO_MOSAIC_CHAIR);
        addDrop(ModBlocks.CRIMSON_CHAIR);
        addDrop(ModBlocks.WARPED_CHAIR);

        addDrop(ModBlocks.OAK_TABLE);
        addDrop(ModBlocks.SPRUCE_TABLE);
        addDrop(ModBlocks.BIRCH_TABLE);
        addDrop(ModBlocks.JUNGLE_TABLE);
        addDrop(ModBlocks.ACACIA_TABLE);
        addDrop(ModBlocks.DARK_OAK_TABLE);
        addDrop(ModBlocks.MANGROVE_TABLE);
        addDrop(ModBlocks.CHERRY_TABLE);
        addDrop(ModBlocks.PALE_OAK_TABLE);
        addDrop(ModBlocks.BAMBOO_TABLE);
        addDrop(ModBlocks.BAMBOO_MOSAIC_TABLE);
        addDrop(ModBlocks.CRIMSON_TABLE);
        addDrop(ModBlocks.WARPED_TABLE);

        addDrop(ModBlocks.TELEPORTER_BLOCK);
    }

    public void addSideDrop(Block block) {
        addDrop(block, LootTable.builder().pool(LootPool.builder()
                .rolls(new ConstantLootNumberProvider(1))
                        .with(ItemEntry.builder(block.asItem())
                                .apply(SetCountLootFunction.builder(ConstantLootNumberProvider.create(2))
                                        .conditionally(BlockStatePropertyLootCondition.builder(block)
                                                .properties(StatePredicate.Builder.create()
                                                        .exactMatch(SideBlock.TYPE, SideType.DOUBLE))))
                                                                .apply(ExplosionDecayLootFunction.builder()))));
    }
}
